#[cfg(checkpoint_sbi_char)]
pub fn checkpoint(checkpoint: Checkpoint) {
    crate::arch::riscv64::sbi::putchar(checkpoint.byte());
}

#[cfg(not(checkpoint_sbi_char))]
pub fn checkpoint(_checkpoint: Checkpoint) {}

#[allow(dead_code)]
#[derive(Clone, Copy, Eq, PartialEq)]
pub enum Checkpoint {
    StartupTimelineStarted,
    #[allow(dead_code)]
    StartupTimelineReady,
    PreparePhaseReady,
    PreparePhaseOnline,
    BootPhaseStarted,
    #[allow(dead_code)]
    BootPhaseReady,
    EntryPreludePhaseStarted,
    #[allow(dead_code)]
    EntryPreludePhaseReady,
    #[allow(dead_code)]
    EntrySuccessorPhaseStarted,
    #[allow(dead_code)]
    EntrySuccessorPhaseReady,
    EntryPreludePhaseDestroyed,
    InterruptStreamPrepared,
    InterruptStreamReady,
    KernelImagePrepared,
    RootStreamPrepared,
    KernelImageReady,
    BootCpuPrepared,
    BootCpuReady,
    BootCpuOnline,
    CpuGroupPrepared,
    InitTaskPrepared,
    InitStackPrepared,
    EventStreamPrepared,
    ExceptionStreamPrepared,
    TrampolineVmReady,
    TrampolineVmOnline,
    TrampolineVmDestroyed,
    RawDtbPrepared,
    RawDtbReady,
    FixMapReady,
    EarlyVmPrepared,
    EarlyVmReady,
    EarlyVmOnline,
    VmPrepared,
    VmReady,
    VmOnline,
    KernelImageOnline,
    EventStreamOnline,
    InitTaskOnline,
    InitStackReady,
    InitStackOnline,
    SocPrepared,
    EarlyDtbPrepared,
    EarlyDtbReady,
    EarlyDtbDestroyed,
    PlatformCpuInfoReady,
    PlatformCpuInfoOnline,
    PhysicalMemoryReady,
    PhysicalMemoryOnline,
    CpuIdMapReady,
    KernelCmdlineReady,
    InitMmReady,
    EarlyIoremapReady,
    SbiReady,
    EarlyParamReady,
    MemBlockPrepared,
    MemBlockReady,
    MemBlockOnline,
    SwapperVmReady,
    SwapperVmOnline,
    EarlyVmDestroyed,
    #[allow(dead_code)]
    PrintkBufferPrepared,
    #[allow(dead_code)]
    EarlyConPrepared,
    #[allow(dead_code)]
    EarlyConReady,
    #[allow(dead_code)]
    EarlyConOnline,
    CorePreparePhaseStarted,
    CorePreparePhaseReady,
    DeviceTreeReady,
    ZonesReady,
    PageAllocatorPrepareReady,
    ResourceTreeReady,
    CpuGroupReady,
    CacheBlockInfoReady,
    RiscvHwCapReady,
    SavedCommandLineReady,
    StaticCommandLineReady,
    SetupNrCpuIdsCheckpoint,
    PerCpuStorageReady,
    BootCpuHotplugStateReady,
    SecondParseEarlyParamCheckpoint,
    BootParamReady,
    PrintUnknownBootoptionsCheckpoint,
    PayloadParamReady,
    RandomnessPrepared,
    PrintkBufferReady,
    ExceptionTableReady,
    ExceptionStreamReady,
    PayloadPhaseReady,
    PayloadPhaseOnline,
}

impl Checkpoint {
    #[allow(dead_code)]
    const fn byte(self) -> u8 {
        match self {
            Self::StartupTimelineStarted => b'[',
            Self::StartupTimelineReady => b']',
            Self::PreparePhaseReady => b'{',
            Self::PreparePhaseOnline => b'}',
            Self::BootPhaseStarted => b'(',
            Self::BootPhaseReady => b')',
            Self::EntryPreludePhaseStarted => b'A',
            Self::EntryPreludePhaseReady => b'a',
            Self::EntrySuccessorPhaseStarted => b'P',
            Self::EntrySuccessorPhaseReady => b'3',
            Self::EntryPreludePhaseDestroyed => b'd',
            Self::InterruptStreamPrepared => b'I',
            Self::InterruptStreamReady => b'i',
            Self::KernelImagePrepared => b'K',
            Self::RootStreamPrepared => b'O',
            Self::KernelImageReady => b'Z',
            Self::BootCpuPrepared => b'H',
            Self::BootCpuReady => b'0',
            Self::BootCpuOnline => b'1',
            Self::CpuGroupPrepared => b'G',
            Self::InitTaskPrepared => b'T',
            Self::InitStackPrepared => b'S',
            Self::EventStreamPrepared => b'V',
            Self::ExceptionStreamPrepared => b'9',
            Self::TrampolineVmReady => b'Q',
            Self::TrampolineVmOnline => b'R',
            Self::TrampolineVmDestroyed => b'X',
            Self::RawDtbPrepared => b'Y',
            Self::RawDtbReady => b'W',
            Self::FixMapReady => b'M',
            Self::EarlyVmPrepared => b'N',
            Self::EarlyVmReady => b'J',
            Self::EarlyVmOnline => b'L',
            Self::VmPrepared => b'U',
            Self::VmReady => b'v',
            Self::VmOnline => b'2',
            Self::KernelImageOnline => b'k',
            Self::EventStreamOnline => b'e',
            Self::InitTaskOnline => b't',
            Self::InitStackReady => b's',
            Self::InitStackOnline => b'n',
            Self::SocPrepared => b'o',
            Self::EarlyDtbPrepared => b'p',
            Self::EarlyDtbReady => b'r',
            Self::EarlyDtbDestroyed => b'g',
            Self::PlatformCpuInfoReady => b'c',
            Self::PlatformCpuInfoOnline => b'5',
            Self::PhysicalMemoryReady => b'm',
            Self::PhysicalMemoryOnline => b'6',
            Self::CpuIdMapReady => b'l',
            Self::KernelCmdlineReady => b'w',
            Self::InitMmReady => b'h',
            Self::EarlyIoremapReady => b'y',
            Self::SbiReady => b'b',
            Self::EarlyParamReady => b'z',
            Self::MemBlockPrepared => b'4',
            Self::MemBlockReady => b'f',
            Self::MemBlockOnline => b'F',
            Self::SwapperVmReady => b'j',
            Self::SwapperVmOnline => b'q',
            Self::EarlyVmDestroyed => b'x',
            Self::PrintkBufferPrepared => b'B',
            Self::EarlyConPrepared => b'C',
            Self::EarlyConReady => b'D',
            Self::EarlyConOnline => b'E',
            Self::CorePreparePhaseStarted => b'!',
            Self::CorePreparePhaseReady => b'@',
            Self::DeviceTreeReady => b'?',
            Self::ZonesReady => b'+',
            Self::PageAllocatorPrepareReady => b'-',
            Self::ResourceTreeReady => b'%',
            Self::CpuGroupReady => b'~',
            Self::CacheBlockInfoReady => b'&',
            Self::RiscvHwCapReady => b'=',
            Self::SavedCommandLineReady => b':',
            Self::StaticCommandLineReady => b';',
            Self::SetupNrCpuIdsCheckpoint => b'<',
            Self::PerCpuStorageReady => b'>',
            Self::BootCpuHotplugStateReady => b'^',
            Self::SecondParseEarlyParamCheckpoint => b'_',
            Self::BootParamReady => b'`',
            Self::PrintUnknownBootoptionsCheckpoint => b'|',
            Self::PayloadParamReady => b'$',
            Self::RandomnessPrepared => b'*',
            Self::PrintkBufferReady => b'/',
            Self::ExceptionTableReady => b'.',
            Self::ExceptionStreamReady => b',',
            Self::PayloadPhaseReady => b'7',
            Self::PayloadPhaseOnline => b'8',
        }
    }
}
