pub fn enable_post_vm_checkpoints() {
    #[cfg(checkpoint_sbi_char)]
    crate::checkpoint::handlers::early_trace::enable_named_checkpoints();
    crate::checkpoint::enable_post_vm_checkpoints();
}

pub fn checkpoint(checkpoint: Checkpoint) {
    crate::checkpoint::dispatch_pre_context(checkpoint);
}

#[allow(dead_code)]
#[derive(Clone, Copy, Eq, PartialEq)]
pub enum Checkpoint {
    StartupTimelineStarted,
    #[allow(dead_code)]
    StartupTimelineReady,
    PreparePhaseReady,
    PreparePhaseOnline,
    BootPhaseStarted,
    #[allow(dead_code)]
    BootPhaseReady,
    InterruptPhaseStarted,
    InterruptPhaseReady,
    EntryPreludePhaseStarted,
    #[allow(dead_code)]
    EntryPreludePhaseReady,
    #[allow(dead_code)]
    EntrySuccessorPhaseStarted,
    #[allow(dead_code)]
    EntrySuccessorPhaseReady,
    EntryPreludePhaseDestroyed,
    InterruptStreamPrepared,
    InterruptStreamReady,
    KernelImagePrepared,
    RootStreamPrepared,
    KernelImageReady,
    BootCurrentCpuReady,
    BootCurrentCpuOnline,
    BootCpuPrepared,
    BootCpuReady,
    BootCpuOnline,
    BootCpuLocalInterruptReady,
    BootCpuCurrentTaskReady,
    CpuGroupPrepared,
    InitTaskPrepared,
    InitStackPrepared,
    EventStreamPrepared,
    ExceptionStreamPrepared,
    TrampolineVmReady,
    TrampolineVmOnline,
    TrampolineVmDestroyed,
    RawDtbPrepared,
    RawDtbReady,
    FixMapReady,
    EarlyVmPrepared,
    EarlyVmReady,
    EarlyVmOnline,
    VmPrepared,
    VmReady,
    VmOnline,
    KernelImageOnline,
    EventStreamReady,
    InitTaskOnline,
    InitStackReady,
    InitStackOnline,
    SocPrepared,
    EarlyDtbPrepared,
    EarlyDtbReady,
    EarlyDtbDestroyed,
    PlatformCpuInfoReady,
    PlatformCpuInfoOnline,
    PhysicalMemoryReady,
    PhysicalMemoryOnline,
    CpuIdMapPrepared,
    CpuIdMapReady,
    CommandLinePrepared,
    KernelCmdlineReady,
    InitMmReady,
    EarlyIoremapReady,
    SbiReady,
    EarlyParamReady,
    MemBlockPrepared,
    MemBlockReady,
    MemBlockOnline,
    MemBlockOffline,
    SwapperVmReady,
    SwapperVmOnline,
    EarlyVmDestroyed,
    #[allow(dead_code)]
    PrintkBufferPrepared,
    #[allow(dead_code)]
    EarlyConPrepared,
    #[allow(dead_code)]
    EarlyConReady,
    #[allow(dead_code)]
    EarlyConOnline,
    EarlyConOffline,
    Serial8250ConsoleOnline,
    Serial8250ConsoleIrqDrivenReady,
    Serial8250ConsoleLongBurstIrqTxReady,
    Serial8250ConsoleTxQuiesceReady,
    Serial8250RxLoopbackReady,
    Serial8250RxBatchLoopbackReady,
    BootConsoleOffline,
    CorePreparePhaseStarted,
    CorePreparePhaseReady,
    DeviceTreeReady,
    ZonesReady,
    ResourceTreeReady,
    CpuGroupReady,
    CacheBlockInfoReady,
    CpuCapabilitiesReady,
    DmaCachePolicyReady,
    StaticBranchReady,
    CommandLineReady,
    SavedCommandLineReady,
    StaticCommandLineReady,
    SetupNrCpuIdsCheckpoint,
    PerCpuStaticImageReady,
    PerCpuFirstChunkReady,
    PerCpuOffsetTableReady,
    PerCpuStorageReady,
    CpuHotplugStateReady,
    SecondParseEarlyParamCheckpoint,
    BootParamReady,
    PrintUnknownBootoptionsCheckpoint,
    PayloadParamReady,
    RandomnessPrepared,
    PrintkBufferReady,
    ExceptionTableReady,
    ExceptionStreamReady,
    MmCoreInitPhaseStarted,
    MmCoreInitPhaseReady,
    MemoryTopologyReady,
    BootMemoryNodeReady,
    BootZoneSetReady,
    PageMetadataMapReady,
    BootZonelistSetReady,
    PageAllocatorPrepared,
    MemoryDebugHardeningReady,
    StackDepotReady,
    SwiotlbReady,
    PageAllocatorReady,
    PageAllocatorMemBlockHandoffReady,
    SlubAllocatorPrepared,
    SlubCacheRegistryReady,
    KmallocCachesReady,
    SlubAllocatorReady,
    KernelGlobalAllocatorReady,
    DynamicContainerRuntimeReady,
    PageTableLockCacheReady,
    PageTableCachesReady,
    VmapAreaCacheReady,
    VmapAddressSpaceReady,
    VmapNodeSetReady,
    VmapBlockQueuesReady,
    VfreeDeferredSetReady,
    VmallocAllocatorReady,
    IoremapReady,
    MmStructCacheReady,
    SchedInitPhaseStarted,
    SchedInitPhaseReady,
    PokingInitNoop,
    FtraceInitNoop,
    DefaultSchedRootDomainReady,
    BitWaitQueueTablePrepared,
    SchedulerPrepared,
    BootRunQueueReady,
    BootIdleTaskReady,
    BootIdlePreemptionReady,
    SchedulerReady,
    SchedulerOnline,
    SchedInitIrqsDisabledCheckpoint,
    RadixTreeReady,
    MapleTreeReady,
    WorkqueuePrepared,
    SoftirqPrepared,
    TasksRcuPrepared,
    RcuCoreReady,
    TraceInitDeferred,
    ContextTrackingInitNoop,
    SchedulerPickNextTaskExit,
    SchedulerSwitchToEntry,
    SchedulerSwitchToExit,
    SchedulerSchedule,
    SchedulerScheduleExit,
    IrqTimeInitPhaseStarted,
    IrqTimeInitPhaseReady,
    IrqControllerReady,
    RiscvIntcReady,
    IrqChipInitTablePrepared,
    PlicDriverPrepared,
    IrqChipInitTableReady,
    IrqDispatchTreeReady,
    PlicReady,
    PlicIrqDomainPrepared,
    PlicIrqDomainReady,
    IrqHandlerRegistryReady,
    TickBroadcastPrepared,
    TickPrepared,
    TimerWheelReady,
    HrtimerCoreReady,
    ClocksourceCorePrepared,
    JiffiesClocksourcePrepared,
    TimekeeperReady,
    RiscvTimerProviderReady,
    TickBroadcastReady,
    TickReady,
    SoftirqReady,
    RandomnessReady,
    IpiMuxReady,
    SbiIpiReady,
    SmpCallFunctionReady,
    InterruptStreamOnline,
    IrqOpenPreparePhaseStarted,
    IrqOpenPreparePhaseReady,
    SlubFlushWorkqueueReady,
    TtyLineDisciplineRegistryPrepared,
    ConsoleDriverSetPrepared,
    ConsolePrepared,
    PanicLaterClearCheckpoint,
    LockdepInitNoop,
    LockingSelftestNoop,
    InitrdBoundsTrimmed,
    PageAllocatorPerCpuPagesetsDeferred,
    NumaPolicyNoop,
    AcpiEarlyNoop,
    LateTimeInitNoop,
    SchedClockReady,
    DelayLoopReady,
    ArchCpuFinalizeNoop,
    ProcessPreparePhaseStarted,
    ProcessPreparePhaseReady,
    RootPidNamespaceReady,
    AnonVmaCoreReady,
    X86EfiRuntimeSwitchTrimmed,
    TaskCreationCorePrepared,
    CredentialCorePrepared,
    VectorContextPrepared,
    UprobeCoreReady,
    TaskCreationCoreReady,
    ShadowCallStackInitNoop,
    LockdepInitTaskNoop,
    SignalCorePrepared,
    TaskFileContextPrepared,
    VmaCorePrepared,
    NsProxyPrepared,
    UtsNamespacePrepared,
    KeyringCoreReady,
    SecurityCoreReady,
    DbgLateInitNoop,
    NetNamespaceDeferred,
    VfsCoreDeferred,
    PageCacheDeferred,
    SignalCoreSetupDeferred,
    SeqFileCoreDeferred,
    ProcfsDeferred,
    NsfsDeferred,
    PidfsDeferred,
    CpusetNoop,
    CgroupNoop,
    TaskstatsNoop,
    DelayAccountingNoop,
    AcpiSubsystemNoop,
    ArchPostAcpiNoop,
    KcsanNoop,
    UpMultitaskPhaseStarted,
    UpMultitaskPhaseReady,
    RestInitPhaseStarted,
    RestInitPhaseReady,
    RcuSchedulerStartingReady,
    KernelInitTaskPiLockReady,
    KthreaddTaskPiLockReady,
    KernelInitTaskPrepared,
    KernelInitTaskReady,
    KernelInitTaskOnline,
    NumaDefaultPolicyNoop,
    KthreaddTaskPrepared,
    KthreaddTaskReady,
    KthreaddTaskOnline,
    KthreaddTaskGlobalRefBound,
    KthreaddTaskScheduleLoopReady,
    SimpleWaitQueueReady,
    CompletionPrepared,
    CompletionReady,
    CompletionOnline,
    SystemStatePrepared,
    SystemStateReady,
    KthreaddReadyGateReady,
    KthreaddReadyGateOnline,
    RestInitDispatchReady,
    BootIdleRuntimeReady,
    PreSmpInitPhaseStarted,
    PreSmpInitPhaseReady,
    PageAllocatorFullGfpMaskOpen,
    CpuGroupPreSmpReady,
    WorkqueueReady,
    VmstatCorePrepared,
    TasksRcuReady,
    PreSmpInitcallsReady,
    PreSmpBoundaryReady,
    SmpRuntimePhaseStarted,
    SmpRuntimePhaseReady,
    SmpBringupPhaseStarted,
    SmpBringupPhaseReady,
    SecondaryIdleTasksPrepared,
    CpuHotplugSyncPrepared,
    CpuStartProviderReady,
    CpuRunningObserved,
    SecondaryCpuStartupAckReady,
    CpuDoneUpObserved,
    SecondaryCpusOnline,
    SecondaryCpuOnlineAckReady,
    SmpBringupBoundaryReady,
    RuntimeCorePhaseStarted,
    RuntimeCorePhaseReady,
    SchedulerSmpReady,
    WorkqueueTopologyReady,
    AsyncCoreDeferredReady,
    PadataCoreDeferredReady,
    PageAllocatorLateReady,
    RuntimeCoreBoundaryReady,
    InitcallPhaseStarted,
    InitcallPhaseReady,
    CpusetSmpTrimmedReady,
    DriverCoreDeferredReady,
    IrqProcViewDeferredReady,
    CtorTableReady,
    OfPlatformDefaultPopulateScanComplete,
    VirtioBusReady,
    VirtioBusDeviceAdded,
    VirtioBlkReady,
    VirtioBlkReadReady,
    VirtioRngEntropyReady,
    InitcallTableReady,
    Serial8250ConsoleBurstIrqTxReady,
    Serial8250ConsoleLongIrqTxReady,
    TtyXmitFifoProbeReady,
    TtyWriteRuntimeTxReady,
    TtyWriteBatchRuntimeTxReady,
    InitcallBoundaryReady,
    RootfsPhaseStarted,
    RootfsPhaseReady,
    KUnitRuntimeTrimmedReady,
    InitramfsSyncDeferredReady,
    RootfsConsoleDeferredReady,
    RamdiskExecuteCommandEaccessCheckpoint,
    RootFSOnline,
    IntegrityKeysDeferredReady,
    RootfsBoundaryReady,
    FinalizePhaseStarted,
    FinalizePhaseReady,
    AsyncFullSyncDeferredReady,
    SystemStateFreeingInitmemCheckpoint,
    InitMemoryCleanupDeferredReady,
    KernelMappingProtectionDeferredReady,
    PtiFinalizeTrimmedReady,
    SystemStateOnline,
    RcuInkernelBootEnded,
    RcuBootEndReady,
    SysctlArgsDeferredReady,
    FinalizeBoundaryReady,
    BreakpointExceptionHandled,
    PayloadPhaseReady,
    PayloadPhaseOnline,
}

impl Checkpoint {
    #[allow(dead_code)]
    pub(crate) const fn early_byte(self) -> u8 {
        match self {
            Self::EntryPreludePhaseStarted => b'A',
            Self::InterruptStreamPrepared => b'I',
            Self::KernelImagePrepared => b'K',
            Self::RootStreamPrepared => b'O',
            Self::KernelImageReady => b'Z',
            Self::BootCpuPrepared => b'H',
            Self::CpuGroupPrepared => b'G',
            Self::InitTaskPrepared => b'T',
            Self::InitStackPrepared => b'S',
            Self::EventStreamPrepared => b'V',
            Self::ExceptionStreamPrepared => b'9',
            Self::TrampolineVmReady => b'Q',
            Self::RawDtbPrepared => b'Y',
            Self::RawDtbReady => b'W',
            Self::FixMapReady => b'M',
            Self::EarlyVmPrepared => b'N',
            Self::EarlyVmReady => b'J',
            Self::VmPrepared => b'U',
            _ => b'?',
        }
    }

    #[allow(dead_code)]
    pub const fn name(self) -> &'static str {
        match self {
            Self::StartupTimelineStarted => "StartupTimeline.Started",
            Self::StartupTimelineReady => "StartupTimeline.Ready",
            Self::PreparePhaseReady => "PreparePhase.Ready",
            Self::PreparePhaseOnline => "PreparePhase.Online",
            Self::BootPhaseStarted => "BootPhase.Started",
            Self::BootPhaseReady => "BootPhase.Ready",
            Self::InterruptPhaseStarted => "InterruptPhase.Started",
            Self::InterruptPhaseReady => "InterruptPhase.Ready",
            Self::EntryPreludePhaseStarted => "EntryPreludePhase.Started",
            Self::EntryPreludePhaseReady => "EntryPreludePhase.Ready",
            Self::EntrySuccessorPhaseStarted => "EntrySuccessorPhase.Started",
            Self::EntrySuccessorPhaseReady => "EntrySuccessorPhase.Ready",
            Self::EntryPreludePhaseDestroyed => "EntryPreludePhase.Destroyed",
            Self::InterruptStreamPrepared => "InterruptStream.Prepared",
            Self::InterruptStreamReady => "InterruptStream.Ready",
            Self::KernelImagePrepared => "KernelImage.Prepared",
            Self::RootStreamPrepared => "RootStream.Prepared",
            Self::KernelImageReady => "KernelImage.Ready",
            Self::BootCurrentCpuReady => "BootCurrentCPU.Ready",
            Self::BootCurrentCpuOnline => "BootCurrentCPU.Online",
            Self::BootCpuPrepared => "BootCPU.Prepared",
            Self::BootCpuReady => "BootCPU.Ready",
            Self::BootCpuOnline => "BootCPU.Online",
            Self::BootCpuLocalInterruptReady => "BootCpuLocalInterrupt.Ready",
            Self::BootCpuCurrentTaskReady => "BootCpuCurrentTask.Ready",
            Self::CpuGroupPrepared => "CpuGroup.Prepared",
            Self::InitTaskPrepared => "InitTask.Prepared",
            Self::InitStackPrepared => "InitStack.Prepared",
            Self::EventStreamPrepared => "EventStream.Prepared",
            Self::ExceptionStreamPrepared => "ExceptionStream.Prepared",
            Self::TrampolineVmReady => "TrampolineVm.Ready",
            Self::TrampolineVmOnline => "TrampolineVm.Online",
            Self::TrampolineVmDestroyed => "TrampolineVm.Destroyed",
            Self::RawDtbPrepared => "RawDtb.Prepared",
            Self::RawDtbReady => "RawDtb.Ready",
            Self::FixMapReady => "FixMap.Ready",
            Self::EarlyVmPrepared => "EarlyVm.Prepared",
            Self::EarlyVmReady => "EarlyVm.Ready",
            Self::EarlyVmOnline => "EarlyVm.Online",
            Self::VmPrepared => "Vm.Prepared",
            Self::VmReady => "Vm.Ready",
            Self::VmOnline => "Vm.Online",
            Self::KernelImageOnline => "KernelImage.Online",
            Self::EventStreamReady => "EventStream.Ready",
            Self::InitTaskOnline => "InitTask.Online",
            Self::InitStackReady => "InitStack.Ready",
            Self::InitStackOnline => "InitStack.Online",
            Self::SocPrepared => "Soc.Prepared",
            Self::EarlyDtbPrepared => "EarlyDtb.Prepared",
            Self::EarlyDtbReady => "EarlyDtb.Ready",
            Self::EarlyDtbDestroyed => "EarlyDtb.Destroyed",
            Self::PlatformCpuInfoReady => "PlatformCpuInfo.Ready",
            Self::PlatformCpuInfoOnline => "PlatformCpuInfo.Online",
            Self::PhysicalMemoryReady => "PhysicalMemory.Ready",
            Self::PhysicalMemoryOnline => "PhysicalMemory.Online",
            Self::CpuIdMapPrepared => "CpuIdMap.Prepared",
            Self::CpuIdMapReady => "CpuIdMap.Ready",
            Self::CommandLinePrepared => "CommandLine.Prepared",
            Self::KernelCmdlineReady => "KernelCmdline.Ready",
            Self::InitMmReady => "InitMM.Ready",
            Self::EarlyIoremapReady => "EarlyIoremap.Ready",
            Self::SbiReady => "SBI.Ready",
            Self::EarlyParamReady => "EarlyParam.Ready",
            Self::MemBlockPrepared => "MemBlock.Prepared",
            Self::MemBlockReady => "MemBlock.Ready",
            Self::MemBlockOnline => "MemBlock.Online",
            Self::MemBlockOffline => "MemBlock.Offline",
            Self::SwapperVmReady => "SwapperVm.Ready",
            Self::SwapperVmOnline => "SwapperVm.Online",
            Self::EarlyVmDestroyed => "EarlyVm.Destroyed",
            Self::PrintkBufferPrepared => "PrintkBuffer.Prepared",
            Self::EarlyConPrepared => "EarlyCon.Prepared",
            Self::EarlyConReady => "EarlyCon.Ready",
            Self::EarlyConOnline => "EarlyCon.Online",
            Self::EarlyConOffline => "EarlyCon.Offline",
            Self::Serial8250ConsoleOnline => "Serial8250Console.Online",
            Self::Serial8250ConsoleIrqDrivenReady => "Serial8250Console.IrqDrivenReady",
            Self::Serial8250RxLoopbackReady => "Serial8250RxLoopback.Ready",
            Self::Serial8250RxBatchLoopbackReady => "Serial8250RxBatchLoopback.Ready",
            Self::BootConsoleOffline => "BootConsole.Offline",
            Self::CorePreparePhaseStarted => "CorePreparePhase.Started",
            Self::CorePreparePhaseReady => "CorePreparePhase.Ready",
            Self::DeviceTreeReady => "DeviceTree.Ready",
            Self::ZonesReady => "Zones.Ready",
            Self::ResourceTreeReady => "ResourceTree.Ready",
            Self::CpuGroupReady => "CpuGroup.Ready",
            Self::CacheBlockInfoReady => "CacheBlockInfo.Ready",
            Self::CpuCapabilitiesReady => "CpuCapabilities.Ready",
            Self::DmaCachePolicyReady => "DmaCachePolicy.Ready",
            Self::StaticBranchReady => "StaticBranch.Ready",
            Self::CommandLineReady => "CommandLine.Ready",
            Self::SavedCommandLineReady => "SavedCommandLine.Ready",
            Self::StaticCommandLineReady => "StaticCommandLine.Ready",
            Self::SetupNrCpuIdsCheckpoint => "SetupNrCpuIds.Checkpoint",
            Self::PerCpuStaticImageReady => "PerCpuStaticImage.Ready",
            Self::PerCpuFirstChunkReady => "PerCpuFirstChunk.Ready",
            Self::PerCpuOffsetTableReady => "PerCpuOffsetTable.Ready",
            Self::PerCpuStorageReady => "PerCpuStorage.Ready",
            Self::CpuHotplugStateReady => "CpuHotplugState.Ready",
            Self::SecondParseEarlyParamCheckpoint => "SecondParseEarlyParam.Checkpoint",
            Self::BootParamReady => "BootParam.Ready",
            Self::PrintUnknownBootoptionsCheckpoint => "PrintUnknownBootoptions.Checkpoint",
            Self::PayloadParamReady => "PayloadParam.Ready",
            Self::RandomnessPrepared => "Randomness.Prepared",
            Self::PrintkBufferReady => "PrintkBuffer.Ready",
            Self::ExceptionTableReady => "ExceptionTable.Ready",
            Self::ExceptionStreamReady => "ExceptionStream.Ready",
            Self::MmCoreInitPhaseStarted => "MmCoreInitPhase.Started",
            Self::MmCoreInitPhaseReady => "MmCoreInitPhase.Ready",
            Self::MemoryTopologyReady => "MemoryTopology.Ready",
            Self::BootMemoryNodeReady => "BootMemoryNode.Ready",
            Self::BootZoneSetReady => "BootZoneSet.Ready",
            Self::PageMetadataMapReady => "PageMetadataMap.Ready",
            Self::BootZonelistSetReady => "BootZonelistSet.Ready",
            Self::PageAllocatorPrepared => "PageAllocator.Prepared",
            Self::MemoryDebugHardeningReady => "MemoryDebugHardening.Ready",
            Self::StackDepotReady => "StackDepot.Ready",
            Self::SwiotlbReady => "Swiotlb.Ready",
            Self::PageAllocatorReady => "PageAllocator.Ready",
            Self::PageAllocatorMemBlockHandoffReady => "PageAllocator.MemBlockHandoffReady",
            Self::SlubAllocatorPrepared => "SlubAllocator.Prepared",
            Self::SlubCacheRegistryReady => "SlubCacheRegistry.Ready",
            Self::KmallocCachesReady => "KmallocCaches.Ready",
            Self::SlubAllocatorReady => "SlubAllocator.Ready",
            Self::KernelGlobalAllocatorReady => "KernelGlobalAllocator.Ready",
            Self::DynamicContainerRuntimeReady => "DynamicContainerRuntime.Ready",
            Self::PageTableLockCacheReady => "PageTableLockCache.Ready",
            Self::PageTableCachesReady => "PageTableCaches.Ready",
            Self::VmapAreaCacheReady => "VmapAreaCache.Ready",
            Self::VmapAddressSpaceReady => "VmapAddressSpace.Ready",
            Self::VmapNodeSetReady => "VmapNodeSet.Ready",
            Self::VmapBlockQueuesReady => "VmapBlockQueues.Ready",
            Self::VfreeDeferredSetReady => "VfreeDeferredSet.Ready",
            Self::VmallocAllocatorReady => "VmallocAllocator.Ready",
            Self::IoremapReady => "Ioremap.Ready",
            Self::MmStructCacheReady => "MmStructCache.Ready",
            Self::SchedInitPhaseStarted => "SchedInitPhase.Started",
            Self::SchedInitPhaseReady => "SchedInitPhase.Ready",
            Self::PokingInitNoop => "PokingInit.Noop",
            Self::FtraceInitNoop => "FtraceInit.Noop",
            Self::DefaultSchedRootDomainReady => "DefaultSchedRootDomain.Ready",
            Self::BitWaitQueueTablePrepared => "BitWaitQueueTable.Prepared",
            Self::SchedulerPrepared => "Scheduler.Prepared",
            Self::BootRunQueueReady => "BootRunQueue.Ready",
            Self::BootIdleTaskReady => "BootIdleTask.Ready",
            Self::BootIdlePreemptionReady => "BootIdlePreemption.Ready",
            Self::SchedulerReady => "Scheduler.Ready",
            Self::SchedulerOnline => "Scheduler.Online",
            Self::SchedInitIrqsDisabledCheckpoint => "SchedInitIrqsDisabled.Checkpoint",
            Self::RadixTreeReady => "RadixTree.Ready",
            Self::MapleTreeReady => "MapleTree.Ready",
            Self::WorkqueuePrepared => "Workqueue.Prepared",
            Self::SoftirqPrepared => "Softirq.Prepared",
            Self::TasksRcuPrepared => "TasksRcu.Prepared",
            Self::RcuCoreReady => "RcuCore.Ready",
            Self::TraceInitDeferred => "TraceInit.Deferred",
            Self::ContextTrackingInitNoop => "ContextTrackingInit.Noop",
            Self::SchedulerPickNextTaskExit => "Scheduler.PickNextTask.Exit",
            Self::SchedulerSwitchToEntry => "Scheduler.SwitchTo.Entry",
            Self::SchedulerSwitchToExit => "Scheduler.SwitchTo.Exit",
            Self::SchedulerSchedule => "Scheduler.Schedule",
            Self::SchedulerScheduleExit => "Scheduler.Schedule.Exit",
            Self::IrqTimeInitPhaseStarted => "IrqTimeInitPhase.Started",
            Self::IrqTimeInitPhaseReady => "IrqTimeInitPhase.Ready",
            Self::IrqControllerReady => "IrqController.Ready",
            Self::RiscvIntcReady => "RiscvIntc.Ready",
            Self::IrqChipInitTablePrepared => "IrqChipInitTable.Prepared",
            Self::PlicDriverPrepared => "PlicDriver.Prepared",
            Self::IrqChipInitTableReady => "IrqChipInitTable.Ready",
            Self::IrqDispatchTreeReady => "IrqDispatchTree.Ready",
            Self::PlicReady => "Plic.Ready",
            Self::PlicIrqDomainPrepared => "PlicIrqDomain.Prepared",
            Self::PlicIrqDomainReady => "PlicIrqDomain.Ready",
            Self::IrqHandlerRegistryReady => "IrqHandlerRegistry.Ready",
            Self::TickBroadcastPrepared => "TickBroadcast.Prepared",
            Self::TickPrepared => "Tick.Prepared",
            Self::TimerWheelReady => "TimerWheel.Ready",
            Self::HrtimerCoreReady => "HrtimerCore.Ready",
            Self::ClocksourceCorePrepared => "ClocksourceCore.Prepared",
            Self::JiffiesClocksourcePrepared => "JiffiesClocksource.Prepared",
            Self::TimekeeperReady => "Timekeeper.Ready",
            Self::RiscvTimerProviderReady => "RiscvTimerProvider.Ready",
            Self::TickBroadcastReady => "TickBroadcast.Ready",
            Self::TickReady => "Tick.Ready",
            Self::SoftirqReady => "Softirq.Ready",
            Self::RandomnessReady => "Randomness.Ready",
            Self::IpiMuxReady => "IpiMux.Ready",
            Self::SbiIpiReady => "SbiIpi.Ready",
            Self::SmpCallFunctionReady => "SmpCallFunction.Ready",
            Self::InterruptStreamOnline => "InterruptStream.Online",
            Self::IrqOpenPreparePhaseStarted => "IrqOpenPreparePhase.Started",
            Self::IrqOpenPreparePhaseReady => "IrqOpenPreparePhase.Ready",
            Self::SlubFlushWorkqueueReady => "SlubAllocator.FlushWorkqueueReady",
            Self::TtyLineDisciplineRegistryPrepared => "TtyLineDisciplineRegistry.Prepared",
            Self::ConsoleDriverSetPrepared => "ConsoleDriverSet.Prepared",
            Self::ConsolePrepared => "Console.Prepared",
            Self::PanicLaterClearCheckpoint => "PanicLater.Clear",
            Self::LockdepInitNoop => "LockdepInit.Noop",
            Self::LockingSelftestNoop => "LockingSelftest.Noop",
            Self::InitrdBoundsTrimmed => "InitrdBounds.Trimmed",
            Self::PageAllocatorPerCpuPagesetsDeferred => "PageAllocator.PerCpuPagesetsDeferred",
            Self::NumaPolicyNoop => "NumaPolicy.Noop",
            Self::AcpiEarlyNoop => "AcpiEarly.Noop",
            Self::LateTimeInitNoop => "LateTimeInit.Noop",
            Self::SchedClockReady => "SchedClock.Ready",
            Self::DelayLoopReady => "DelayLoop.Ready",
            Self::ArchCpuFinalizeNoop => "ArchCpuFinalize.Noop",
            Self::ProcessPreparePhaseStarted => "ProcessPreparePhase.Started",
            Self::ProcessPreparePhaseReady => "ProcessPreparePhase.Ready",
            Self::RootPidNamespaceReady => "RootPidNamespace.Ready",
            Self::AnonVmaCoreReady => "AnonVmaCore.Ready",
            Self::X86EfiRuntimeSwitchTrimmed => "X86EfiRuntimeSwitch.Trimmed",
            Self::TaskCreationCorePrepared => "TaskCreationCore.Prepared",
            Self::CredentialCorePrepared => "CredentialCore.Prepared",
            Self::VectorContextPrepared => "VectorContext.Prepared",
            Self::UprobeCoreReady => "UprobeCore.Ready",
            Self::TaskCreationCoreReady => "TaskCreationCore.Ready",
            Self::ShadowCallStackInitNoop => "ShadowCallStackInit.Noop",
            Self::LockdepInitTaskNoop => "LockdepInitTask.Noop",
            Self::SignalCorePrepared => "SignalCore.Prepared",
            Self::TaskFileContextPrepared => "TaskFileContext.Prepared",
            Self::VmaCorePrepared => "VmaCore.Prepared",
            Self::NsProxyPrepared => "NsProxy.Prepared",
            Self::UtsNamespacePrepared => "UtsNamespace.Prepared",
            Self::KeyringCoreReady => "KeyringCore.Ready",
            Self::SecurityCoreReady => "SecurityCore.Ready",
            Self::DbgLateInitNoop => "DbgLateInit.Noop",
            Self::NetNamespaceDeferred => "NetNamespace.Deferred",
            Self::VfsCoreDeferred => "VfsCore.Deferred",
            Self::PageCacheDeferred => "PageCache.Deferred",
            Self::SignalCoreSetupDeferred => "SignalCore.SetupDeferred",
            Self::SeqFileCoreDeferred => "SeqFileCore.Deferred",
            Self::ProcfsDeferred => "Procfs.Deferred",
            Self::NsfsDeferred => "Nsfs.Deferred",
            Self::PidfsDeferred => "Pidfs.Deferred",
            Self::CpusetNoop => "Cpuset.Noop",
            Self::CgroupNoop => "Cgroup.Noop",
            Self::TaskstatsNoop => "Taskstats.Noop",
            Self::DelayAccountingNoop => "DelayAccounting.Noop",
            Self::AcpiSubsystemNoop => "AcpiSubsystem.Noop",
            Self::ArchPostAcpiNoop => "ArchPostAcpi.Noop",
            Self::KcsanNoop => "Kcsan.Noop",
            Self::UpMultitaskPhaseStarted => "UpMultitaskPhase.Started",
            Self::UpMultitaskPhaseReady => "UpMultitaskPhase.Ready",
            Self::RestInitPhaseStarted => "RestInitPhase.Started",
            Self::RestInitPhaseReady => "RestInitPhase.Ready",
            Self::RcuSchedulerStartingReady => "RcuCore.SchedulerStartingReady",
            Self::KernelInitTaskPiLockReady => "KernelInitTaskPiLock.Ready",
            Self::KthreaddTaskPiLockReady => "KthreaddTaskPiLock.Ready",
            Self::KernelInitTaskPrepared => "KernelInitTask.Prepared",
            Self::KernelInitTaskReady => "KernelInitTask.Ready",
            Self::KernelInitTaskOnline => "KernelInitTask.Online",
            Self::NumaDefaultPolicyNoop => "NumaDefaultPolicy.Noop",
            Self::KthreaddTaskPrepared => "KthreaddTask.Prepared",
            Self::KthreaddTaskReady => "KthreaddTask.Ready",
            Self::KthreaddTaskOnline => "KthreaddTask.Online",
            Self::KthreaddTaskGlobalRefBound => "KthreaddTask.GlobalRefBound",
            Self::KthreaddTaskScheduleLoopReady => "KthreaddTask.ScheduleLoopReady",
            Self::SimpleWaitQueueReady => "SimpleWaitQueue.Ready",
            Self::CompletionPrepared => "Completion.Prepared",
            Self::CompletionReady => "Completion.Ready",
            Self::CompletionOnline => "Completion.Online",
            Self::SystemStatePrepared => "SystemState.Prepared",
            Self::SystemStateReady => "SystemState.Ready",
            Self::KthreaddReadyGateReady => "KthreaddReadyGate.Ready",
            Self::KthreaddReadyGateOnline => "KthreaddReadyGate.Online",
            Self::RestInitDispatchReady => "RestInit.DispatchReady",
            Self::BootIdleRuntimeReady => "BootIdleRuntime.Ready",
            Self::PreSmpInitPhaseStarted => "PreSmpInitPhase.Started",
            Self::PreSmpInitPhaseReady => "PreSmpInitPhase.Ready",
            Self::PageAllocatorFullGfpMaskOpen => "PageAllocator.FullGfpMaskOpen",
            Self::CpuGroupPreSmpReady => "CpuGroup.PreSmpReady",
            Self::WorkqueueReady => "Workqueue.Ready",
            Self::VmstatCorePrepared => "VmstatCore.Prepared",
            Self::TasksRcuReady => "TasksRcu.Ready",
            Self::PreSmpInitcallsReady => "PreSmpInitcalls.Ready",
            Self::PreSmpBoundaryReady => "PreSmpBoundary.Ready",
            Self::SmpRuntimePhaseStarted => "SmpRuntimePhase.Started",
            Self::SmpRuntimePhaseReady => "SmpRuntimePhase.Ready",
            Self::SmpBringupPhaseStarted => "SmpBringupPhase.Started",
            Self::SmpBringupPhaseReady => "SmpBringupPhase.Ready",
            Self::SecondaryIdleTasksPrepared => "SecondaryIdleTasks.Prepared",
            Self::CpuHotplugSyncPrepared => "CpuHotplugSync.Prepared",
            Self::CpuStartProviderReady => "CpuStartProvider.Ready",
            Self::CpuRunningObserved => "CpuHotplugSync.CpuRunningObserved",
            Self::SecondaryCpuStartupAckReady => "SecondaryCpuStartupAck.Ready",
            Self::CpuDoneUpObserved => "CpuHotplugSync.DoneUpObserved",
            Self::SecondaryCpusOnline => "CpuGroup.SecondaryCpusOnline",
            Self::SecondaryCpuOnlineAckReady => "SecondaryCpuOnlineAck.Ready",
            Self::SmpBringupBoundaryReady => "SmpBringupBoundary.Ready",
            Self::RuntimeCorePhaseStarted => "RuntimeCorePhase.Started",
            Self::RuntimeCorePhaseReady => "RuntimeCorePhase.Ready",
            Self::SchedulerSmpReady => "Scheduler.SmpReady",
            Self::WorkqueueTopologyReady => "Workqueue.TopologyReady",
            Self::AsyncCoreDeferredReady => "AsyncCore.DeferredReady",
            Self::PadataCoreDeferredReady => "PadataCore.DeferredReady",
            Self::PageAllocatorLateReady => "PageAllocator.LateReady",
            Self::RuntimeCoreBoundaryReady => "RuntimeCoreBoundary.Ready",
            Self::InitcallPhaseStarted => "InitcallPhase.Started",
            Self::InitcallPhaseReady => "InitcallPhase.Ready",
            Self::CpusetSmpTrimmedReady => "CpusetSmp.TrimmedReady",
            Self::DriverCoreDeferredReady => "DriverCore.DeferredReady",
            Self::IrqProcViewDeferredReady => "IrqProcView.DeferredReady",
            Self::CtorTableReady => "CtorTable.Ready",
            Self::OfPlatformDefaultPopulateScanComplete => "OfPlatformDefaultPopulate.ScanComplete",
            Self::VirtioBusReady => "VirtioBus.Ready",
            Self::VirtioBusDeviceAdded => "VirtioBus.DeviceAdded",
            Self::VirtioBlkReady => "VirtioBlk.Ready",
            Self::VirtioBlkReadReady => "VirtioBlk.ReadReady",
            Self::VirtioRngEntropyReady => "VirtioRng.EntropyReady",
            Self::InitcallTableReady => "InitcallTable.Ready",
            Self::Serial8250ConsoleBurstIrqTxReady => "Serial8250ConsoleBurstIrqTx.Ready",
            Self::Serial8250ConsoleLongIrqTxReady => "Serial8250ConsoleLongIrqTx.Ready",
            Self::Serial8250ConsoleLongBurstIrqTxReady => "Serial8250ConsoleLongBurstIrqTx.Ready",
            Self::Serial8250ConsoleTxQuiesceReady => "Serial8250ConsoleTxQuiesce.Ready",
            Self::TtyXmitFifoProbeReady => "TtyXmitFifoProbe.Ready",
            Self::TtyWriteRuntimeTxReady => "TtyWriteRuntimeTx.Ready",
            Self::TtyWriteBatchRuntimeTxReady => "TtyWriteBatchRuntimeTx.Ready",
            Self::InitcallBoundaryReady => "InitcallBoundary.Ready",
            Self::RootfsPhaseStarted => "RootfsPhase.Started",
            Self::RootfsPhaseReady => "RootfsPhase.Ready",
            Self::KUnitRuntimeTrimmedReady => "KUnitRuntime.TrimmedReady",
            Self::InitramfsSyncDeferredReady => "InitramfsSync.DeferredReady",
            Self::RootfsConsoleDeferredReady => "RootfsConsole.DeferredReady",
            Self::RamdiskExecuteCommandEaccessCheckpoint => {
                "RamdiskExecuteCommand.EaccessCheckpoint"
            }
            Self::RootFSOnline => "RootFS.Online",
            Self::IntegrityKeysDeferredReady => "IntegrityKeys.DeferredReady",
            Self::RootfsBoundaryReady => "RootfsBoundary.Ready",
            Self::FinalizePhaseStarted => "FinalizePhase.Started",
            Self::FinalizePhaseReady => "FinalizePhase.Ready",
            Self::AsyncFullSyncDeferredReady => "AsyncFullSync.DeferredReady",
            Self::SystemStateFreeingInitmemCheckpoint => "SystemState.FreeingInitmemCheckpoint",
            Self::InitMemoryCleanupDeferredReady => "InitMemoryCleanup.DeferredReady",
            Self::KernelMappingProtectionDeferredReady => "KernelMappingProtection.DeferredReady",
            Self::PtiFinalizeTrimmedReady => "PtiFinalize.TrimmedReady",
            Self::SystemStateOnline => "SystemState.Online",
            Self::RcuInkernelBootEnded => "RcuCore.InkernelBootEnded",
            Self::RcuBootEndReady => "RcuBootEnd.Ready",
            Self::SysctlArgsDeferredReady => "SysctlArgs.DeferredReady",
            Self::FinalizeBoundaryReady => "FinalizeBoundary.Ready",
            Self::BreakpointExceptionHandled => "BreakpointException.Handled",
            Self::PayloadPhaseReady => "PayloadPhase.Ready",
            Self::PayloadPhaseOnline => "PayloadPhase.Online",
        }
    }
}
