pub mod handlers;
#[cfg(any(
    checkpoint_handler_announce,
    checkpoint_handler_page_allocator,
    checkpoint_handler_earlycon,
    checkpoint_handler_kernel_init_task,
    checkpoint_handler_linux_plic,
    checkpoint_handler_scheduler_action,
    checkpoint_handler_slub,
    checkpoint_handler_console_handoff,
    checkpoint_handler_uart_irq_chain,
    checkpoint_handler_virtio_bus,
    checkpoint_handler_virtio_blk,
    checkpoint_handler_virtio_rng,
    checkpoint_handler_user_boot,
    checkpoint_handler_user_boot_failure,
    checkpoint_handler_of_platform
))]
mod kunit;

use core::sync::atomic::{AtomicBool, Ordering};

pub use self::handlers::CheckpointOutcome;
use crate::context::Context;

static POST_VM_CHECKPOINTS_ENABLED: AtomicBool = AtomicBool::new(false);
static CHECKPOINT_HANDLER_ACTIVE: AtomicBool = AtomicBool::new(false);

pub fn enable_post_vm_checkpoints() {
    #[cfg(checkpoint_handler_announce)]
    handlers::announce::enable_named_announcements();
    POST_VM_CHECKPOINTS_ENABLED.store(true, Ordering::Release);
}

pub fn checkpoint(checkpoint: Checkpoint) {
    dispatch_pre_context(checkpoint);
}

pub fn ap_checkpoint(checkpoint: Checkpoint, logical_id: usize) {
    #[cfg(checkpoint_handler_announce)]
    handlers::announce::emit_with_ap_idle_task(checkpoint, logical_id);

    #[cfg(not(checkpoint_handler_announce))]
    {
        let _ = checkpoint;
        let _ = logical_id;
    }
}

pub fn dispatch_pre_context(_checkpoint: Checkpoint) {
    #[cfg(checkpoint_handler_announce)]
    {
        if POST_VM_CHECKPOINTS_ENABLED.load(Ordering::Acquire) {
            handlers::announce::emit_with_context(_checkpoint, crate::context::context_ref());
        } else {
            handlers::announce::emit(_checkpoint);
        }
    }
}

pub fn dispatch(checkpoint: Checkpoint, ctx: &Context) {
    dispatch_inner(checkpoint, ctx, true);
}

pub fn dispatch_after_trace(checkpoint: Checkpoint, ctx: &Context) {
    dispatch_inner(checkpoint, ctx, false);
}

fn dispatch_inner(checkpoint: Checkpoint, ctx: &Context, include_announce: bool) {
    if !POST_VM_CHECKPOINTS_ENABLED.load(Ordering::Acquire) || !handlers::has_post_vm_handlers() {
        return;
    }

    if CHECKPOINT_HANDLER_ACTIVE.swap(true, Ordering::AcqRel) {
        checkpoint_reentry_shutdown();
    }

    let outcome = if include_announce {
        handlers::dispatch(checkpoint, ctx)
    } else {
        handlers::dispatch_without_announce(checkpoint, ctx)
    };
    CHECKPOINT_HANDLER_ACTIVE.store(false, Ordering::Release);
    apply_outcome(checkpoint, outcome);
}

fn apply_outcome(checkpoint: Checkpoint, outcome: CheckpointOutcome) {
    match outcome {
        CheckpointOutcome::Continue => {}
        CheckpointOutcome::Passed => {}
        CheckpointOutcome::FailAndShutdown => {
            crate::arch::riscv64::sbi::putstr("# checkpoint fail: ");
            crate::arch::riscv64::sbi::putstr(checkpoint.name());
            crate::arch::riscv64::sbi::putchar(b'\n');
            crate::arch::riscv64::sbi::system_shutdown();
        }
        CheckpointOutcome::StopAndShutdown => {
            crate::arch::riscv64::sbi::putstr("# checkpoint stop: ");
            crate::arch::riscv64::sbi::putstr(checkpoint.name());
            crate::arch::riscv64::sbi::putchar(b'\n');
            crate::arch::riscv64::sbi::system_shutdown();
        }
    }
}

fn checkpoint_reentry_shutdown() -> ! {
    crate::arch::riscv64::sbi::putstr("checkpoint reentry\n");
    crate::arch::riscv64::sbi::system_shutdown()
}

#[allow(dead_code)]
#[derive(Clone, Copy, Eq, PartialEq)]
// Names are external interfaces; numeric IDs are the current dense enum order.
#[allow(clippy::enum_variant_names)]
pub enum Checkpoint {
    KernelStarted,
    BootTaskOnCpu,
    KernelOnline,
    BootInitFlowStarted,
    PreparePhaseReady,
    PreparePhaseOnline,
    EntrySuccessorPhaseStarted,
    #[allow(dead_code)]
    EntrySuccessorPhaseReady,
    #[allow(dead_code)]
    EntrySuccessorPhaseOnline,
    InterruptTypePrepared,
    InterruptTypeReady,
    KernelImagePrepared,
    KernelImageReady,
    BootCpuPrepared,
    BootCpuReady,
    BootCpuOnline,
    BootCpuLocalInterruptReady,
    CpuGroupPrepared,
    InitStackPrepared,
    TrapTypePrepared,
    ExceptionTypePrepared,
    TrampolineVmReady,
    TrampolineVmOnline,
    TrampolineVmDestroyed,
    RawDtbPrepared,
    RawDtbReady,
    FixMapReady,
    EarlyVmPrepared,
    EarlyVmReady,
    EarlyVmOnline,
    VmPrepared,
    VmReady,
    VmOnline,
    KernelImageOnline,
    TrapTypeReady,
    InitStackReady,
    InitStackOnline,
    SocPrepared,
    EarlyDtbPrepared,
    EarlyDtbReady,
    EarlyDtbDestroyed,
    PlatformCpuInfoReady,
    PlatformCpuInfoOnline,
    PhysicalMemoryReady,
    PhysicalMemoryOnline,
    CommandLinePrepared,
    KernelCmdlineReady,
    InitMmReady,
    EarlyIoremapReady,
    SbiReady,
    EarlyParamReady,
    MemBlockPrepared,
    MemBlockReady,
    MemBlockOnline,
    MemBlockOffline,
    SwapperVmReady,
    SwapperVmOnline,
    EarlyVmDestroyed,
    #[allow(dead_code)]
    PrintkBufferPrepared,
    #[allow(dead_code)]
    EarlyConPrepared,
    #[allow(dead_code)]
    EarlyConReady,
    #[allow(dead_code)]
    EarlyConOnline,
    EarlyConOffline,
    Serial8250ConsoleOnline,
    Serial8250ConsoleIrqDrivenReady,
    Serial8250ConsoleLongBurstIrqTxReady,
    Serial8250ConsoleTxQuiesceReady,
    Serial8250RxLoopbackReady,
    Serial8250RxBatchLoopbackReady,
    BootConsoleOffline,
    CorePreparePhaseStarted,
    CorePreparePhaseReady,
    #[allow(dead_code)]
    CorePreparePhaseOnline,
    DeviceTreeReady,
    ZonesReady,
    ResourceTreeReady,
    CpuGroupReady,
    CacheBlockInfoReady,
    CpuCapabilitiesReady,
    DmaCachePolicyReady,
    StaticBranchReady,
    CommandLineReady,
    SavedCommandLineReady,
    StaticCommandLineReady,
    SetupNrCpuIdsCheckpoint,
    PerCpuStaticImageReady,
    PerCpuFirstChunkReady,
    PerCpuOffsetTableReady,
    PerCpuStorageReady,
    CpuHotplugStateReady,
    SecondParseEarlyParamCheckpoint,
    BootParamReady,
    PrintUnknownBootoptionsCheckpoint,
    PayloadParamReady,
    RandomnessPrepared,
    PrintkBufferReady,
    ExceptionTableReady,
    ExceptionTypeReady,
    MmCoreInitPhaseStarted,
    MmCoreInitPhaseReady,
    #[allow(dead_code)]
    MmCoreInitPhaseOnline,
    MemoryTopologyReady,
    MemoryNodeReady,
    ZoneSetReady,
    PageMetadataMapReady,
    ZonelistSetReady,
    PageAllocatorPrepared,
    MemoryDebugHardeningReady,
    StackDepotReady,
    SwiotlbReady,
    PageAllocatorReady,
    PageAllocatorMemBlockHandoffReady,
    SlubSubsystemPrepared,
    SlubCacheRegistryReady,
    KmallocCachesReady,
    SlubSubsystemReady,
    KernelGlobalAllocatorReady,
    DynamicContainerRuntimeReady,
    PageTableLockCacheReady,
    PageTableCachesReady,
    VmapAreaCacheReady,
    VmapAddressSpaceReady,
    VmapNodeSetReady,
    VmapBlockQueuesReady,
    VfreeDeferredSetReady,
    VmallocAllocatorReady,
    IoremapReady,
    MmStructCacheReady,
    MmCoreTrimmedPathsReady,
    SchedInitPhaseStarted,
    SchedInitPhaseReady,
    #[allow(dead_code)]
    SchedInitPhaseOnline,
    PokingInitNoop,
    FtraceInitTrimmedNoop,
    EarlyTraceInitDeferred,
    SchedInitPreludeTrimmedPathsReady,
    DefaultSchedRootDomainReady,
    BitWaitQueueTablePrepared,
    BootIdleRcuReadSidePrepared,
    SchedulerPrepared,
    BootRunQueueReady,
    BootRunQueueLockReady,
    BootInitPreemptionReady,
    BootIdleSetupReady,
    BootIdlePiLockReady,
    BootIdlePreemptionReady,
    SchedulerReady,
    SchedulerOnline,
    SchedInitIrqsDisabledCheckpoint,
    RadixTreeReady,
    MapleTreeReady,
    WorkqueuePrepared,
    SoftirqPrepared,
    TasksRcuPrepared,
    RcuCoreReady,
    TraceInitDeferred,
    ContextTrackingInitTrimmedNoop,
    SchedInitTraceContextBoundariesReady,
    SchedulerPickNextTaskExit,
    SchedulerSwitchToEntry,
    SchedulerSwitchToExit,
    SchedulerSchedule,
    SchedulerScheduleExit,
    IrqTimeInitPhaseStarted,
    IrqTimeInitPhaseReady,
    IrqTimeInitPhaseOnline,
    IrqControllerReady,
    RiscvIntcReady,
    RiscvIrqStackSetReady,
    IrqChipInitTablePrepared,
    PlicDriverPrepared,
    IrqChipInitTableReady,
    IrqDispatchTreeReady,
    PlicReady,
    PlicIrqDomainPrepared,
    PlicIrqDomainReady,
    IrqHandlerRegistryReady,
    TickBroadcastPrepared,
    TickPrepared,
    RcuInitNohzTrimmedNoop,
    IrqTimeTrimmedPathsPrepared,
    TimerWheelReady,
    SrcuCoreReady,
    HrtimerCoreReady,
    ClocksourceCorePrepared,
    JiffiesClocksourcePrepared,
    TimekeeperReady,
    RiscvTimerProviderReady,
    TickBroadcastReady,
    TickReady,
    SoftirqReady,
    RandomnessReady,
    KfenceInitTrimmedNoop,
    IrqTimeTrimmedPathsReady,
    BootStackCanaryReady,
    PerfEventCoreReady,
    ProfileCoreReady,
    IpiMuxReady,
    SbiIpiReady,
    SmpCallFunctionReady,
    LocalIrqEnablePhaseStarted,
    LocalIrqEnablePhaseReady,
    InterruptTypeOnline,
    IrqOpenPreparePhaseStarted,
    IrqOpenPreparePhaseReady,
    SlubFlushWorkqueueReady,
    TtyLineDisciplineRegistryPrepared,
    ConsoleDriverSetPrepared,
    ConsolePrepared,
    IrqOpenPrepareTrimmedPathsPrepared,
    IrqOpenPrepareTrimmedPathsReady,
    PanicLaterClearCheckpoint,
    LockdepInitNoop,
    LockingSelftestNoop,
    InitrdBoundsTrimmed,
    PageAllocatorPerCpuPagesetsDeferred,
    NumaPolicyNoop,
    AcpiEarlyNoop,
    LateTimeInitNoop,
    SchedClockReady,
    DelayLoopReady,
    ArchCpuFinalizeNoop,
    ProcessPreparePhaseStarted,
    ProcessPreparePhaseReady,
    RootPidNamespaceReady,
    AnonVmaCoreReady,
    X86EfiRuntimeSwitchTrimmed,
    TaskCreationCorePrepared,
    CredentialCorePrepared,
    VectorContextPrepared,
    UprobeCoreReady,
    TaskCreationCoreReady,
    ShadowCallStackInitNoop,
    LockdepInitTaskNoop,
    SignalCorePrepared,
    TaskFileContextPrepared,
    VmaCorePrepared,
    NsProxyPrepared,
    UtsNamespacePrepared,
    KeyringCoreReady,
    SecurityCoreReady,
    ProcessPrepareTrimmedPathsPrepared,
    DbgLateInitNoop,
    NetNamespaceDeferred,
    PageCacheDeferred,
    SignalCoreSetupDeferred,
    SeqFileCoreDeferred,
    ProcfsDeferred,
    NsfsDeferred,
    PidfsDeferred,
    CpusetNoop,
    CgroupNoop,
    TaskstatsNoop,
    DelayAccountingNoop,
    AcpiSubsystemNoop,
    ArchPostAcpiNoop,
    KcsanNoop,
    BootInitFlowPrepared,
    BootInitFlowReady,
    BootInitRestInitPhaseReady,
    BootInitScheduleHandoffPhaseReady,
    BootIdleEntryPhaseReady,
    RcuSchedulerStartingReady,
    KernelInitTaskPiLockReady,
    KthreaddTaskPiLockReady,
    KthreaddReadyGateWaitLockReady,
    KernelInitTaskPrepared,
    KernelInitTaskReady,
    KernelInitTaskOnline,
    NumaDefaultPolicyNoop,
    KthreaddTaskPrepared,
    KthreaddTaskReady,
    KthreaddTaskOnline,
    KthreaddTaskGlobalRefBound,
    SimpleWaitQueueReady,
    CompletionPrepared,
    CompletionReady,
    CompletionOnline,
    SystemStatePrepared,
    SystemStateReady,
    KthreaddReadyGateReady,
    KthreaddReadyGateOnline,
    BootIdleFlowReady,
    PreSmpInitPhaseStarted,
    PreSmpInitPhaseReady,
    PageAllocatorFullGfpMaskOpen,
    CpuGroupPreSmpReady,
    WorkqueueReady,
    VmstatCorePrepared,
    TasksRcuReady,
    PreSmpInitcallsReady,
    PreSmpBoundaryReady,
    SmpBringupPhaseStarted,
    SmpBringupPhaseReady,
    SecondaryIdleTasksPrepared,
    SmpbootThreadsLockReady,
    CpuHotplugSyncPrepared,
    CpuHotplugReadGuardUsed,
    SmpbootThreadsMutexGuardUsed,
    CpuAddRemoveLockReady,
    CpuHotplugWriteGuardUsed,
    CpuRunningWaitLockReady,
    CpuDoneUpWaitLockReady,
    CpuStartProviderReady,
    CpuStartProviderBootDataSelected,
    CpuStartProviderBootDataPublished,
    CpuStartProviderHsmStartIssued,
    CpuStartProviderHsmStartReturned,
    ApEntryPreludePhaseStarted,
    ApEntryPreludeBootDataConsumed,
    ApEntryPreludeCurrentStackEstablished,
    ApEntryPreludePhaseReady,
    ApSmpCallinPhaseStarted,
    ApSmpCallinCpuRunningProduced,
    ApSmpCallinPhaseReady,
    ApOnlineIdlePhaseStarted,
    ApOnlineIdleDoneUpProduced,
    ApOnlineIdlePhaseReady,
    CpuRunningObserved,
    CpuRunningWaitLockGuardUsed,
    SecondaryCpuStartupAckReady,
    CpuDoneUpObserved,
    CpuDoneUpWaitLockGuardUsed,
    SecondaryCpusOnline,
    SecondaryCpuApLocalSyncSummary,
    SecondaryCpuOnlineAckReady,
    SmpBringupBoundaryReady,
    RuntimeCorePhaseStarted,
    RuntimeCorePhaseReady,
    SchedulerSmpReady,
    WorkqueueTopologyReady,
    AsyncCoreDeferredReady,
    PadataCoreDeferredReady,
    PageAllocatorLateReady,
    RuntimeCoreBoundaryReady,
    InitcallPhaseStarted,
    InitcallPhaseReady,
    CpusetSmpTrimmedReady,
    DriverCoreDeferredReady,
    IrqProcViewDeferredReady,
    CtorTableReady,
    OfPlatformDefaultPopulateScanComplete,
    VirtioBusReady,
    VirtioBusDeviceAdded,
    VirtioBlkReady,
    VirtioBlkReadReady,
    VirtioBlkLiveReadSubmitted,
    VirtioBlkLiveReadCompleted,
    VirtioRngEntropyReady,
    InitcallTableReady,
    Serial8250ConsoleBurstIrqTxReady,
    Serial8250ConsoleLongIrqTxReady,
    TtyXmitFifoProbeReady,
    TtyWriteRuntimeTxReady,
    TtyWriteBatchRuntimeTxReady,
    InitcallBoundaryReady,
    RootfsPhaseStarted,
    RootfsPhaseReady,
    KUnitRuntimeTrimmedReady,
    InitramfsSyncDeferredReady,
    RootfsConsoleDeferredReady,
    RootfsPrepareNamespacePathsReady,
    RamdiskExecuteCommandEaccessCheckpoint,
    RootFSOnline,
    IntegrityKeysDeferredReady,
    RootfsBoundaryReady,
    FinalizePhaseStarted,
    FinalizePhaseReady,
    AsyncFullSyncDeferredReady,
    SystemStateFreeingInitmemCheckpoint,
    InitMemoryCleanupDeferredReady,
    KernelMappingProtectionDeferredReady,
    PtiFinalizeTrimmedReady,
    SystemStateOnline,
    RcuInkernelBootEnded,
    RcuBootEndReady,
    SysctlArgsDeferredReady,
    FinalizeBoundaryReady,
    BreakpointExceptionHandled,
    UserBootMainElfReady,
    UserBootInterpreterReady,
    UserBootInitAttemptFailed,
    UserBootAddressSpaceSetupStart,
    UserAppFlowEnterUserMode,
    UserAddressSpaceReady,
    SyscallTableExecveArgsReady,
    UserExecMainElfReady,
    UserExecInterpreterReady,
    UserExecAddressSpaceReady,
    UserExecTrapFrameReady,
    UserExecSatpReady,
    UserExecContextReplaced,
    UserExecSatpSwitched,
    UserExecReturnFrameReady,
    SyscallTableOpenAt,
    SyscallTableRead,
    SyscallTableWrite,
    SyscallTableWritev,
    SyscallTableClose,
    SyscallTableNewFstatAt,
    SyscallTableSetTidAddress,
    SyscallTableClone,
    SyscallTableCloneVforkVm,
    SyscallTableCloneVforkPidfd,
    FilesStructPidfdInstall,
    UserCloneVforkChildHandoff,
    UserCloneVforkNextChildAccepted,
    SyscallTableRtSigtimedwait,
    UserSignalWaitSleep,
    UserSignalWaitWakeSigchld,
    UserPidfdReady,
    SyscallTableRtSigtimedwaitReturnSignal,
    SyscallTableWait4,
    UserChildParentWaitResumed,
    UserCloneVforkParentResumed,
    UserChildRecordArchived,
    UserTaskRecordReleased,
    UserChildRecordReaped,
    SyscallTableExit,
    EntrySuccessorPhasePrepared,
    CorePreparePhasePrepared,
    MmCoreInitPhasePrepared,
    SchedInitPhasePrepared,
    IrqTimeInitPhasePrepared,
    LocalIrqEnablePhasePrepared,
    LocalIrqEnablePhaseOnline,
    IrqOpenPreparePhasePrepared,
    IrqOpenPreparePhaseOnline,
    ProcessPreparePhasePrepared,
    ProcessPreparePhaseOnline,
    BootInitFlowOnline,
    BootInitRestInitPhaseStarted,
    BootInitRestInitPhasePrepared,
    BootInitRestInitPhaseOnline,
    BootInitScheduleHandoffPhaseStarted,
    BootInitScheduleHandoffPhasePrepared,
    BootInitScheduleHandoffPhaseOnline,
    BootIdleEntryPhaseStarted,
    BootIdleEntryPhasePrepared,
    BootIdleEntryPhaseOnline,
    PreSmpInitPhasePrepared,
    PreSmpInitPhaseOnline,
    SmpBringupPhasePrepared,
    SmpBringupPhaseOnline,
    RuntimeCorePhasePrepared,
    RuntimeCorePhaseOnline,
    InitcallPhasePrepared,
    InitcallPhaseOnline,
    RootfsPhasePrepared,
    RootfsPhaseOnline,
    FinalizePhasePrepared,
    FinalizePhaseOnline,
    ApEntryPreludePhasePrepared,
    ApEntryPreludePhaseOnline,
    ApSmpCallinPhasePrepared,
    ApSmpCallinPhaseOnline,
    ApOnlineIdlePhasePrepared,
    ApOnlineIdlePhaseOnline,
    PayloadPreparePhaseStarted,
    PayloadPreparePhasePrepared,
    PayloadPreparePhaseReady,
    PayloadPreparePhaseOnline,
    PayloadHandoffPreparePhaseStarted,
    PayloadHandoffPreparePhasePrepared,
    PayloadHandoffPreparePhaseReady,
    PayloadHandoffPreparePhaseOnline,
    KernelInitFlowPayloadHandoffCommitted,
    UserStackGrowComplete,
    UserStackGrowRejected,
    KernelInitFlowOffline,
    KernelInitFlowDestroyed,
    UserAppFlowPrepared,
    UserAppFlowReady,
    UserAppFlowOnline,
}

impl Checkpoint {
    #[allow(dead_code)]
    pub(crate) const fn early_byte(self) -> u8 {
        match self {
            Self::KernelStarted => b'R',
            Self::BootTaskOnCpu => b'T',
            Self::KernelOnline => b'L',
            Self::BootInitFlowStarted => b'O',
            Self::InterruptTypePrepared => b'I',
            Self::KernelImagePrepared => b'K',
            Self::KernelImageReady => b'Z',
            Self::BootCpuPrepared => b'H',
            Self::CpuGroupPrepared => b'G',
            Self::InitStackPrepared => b'S',
            Self::TrapTypePrepared => b'V',
            Self::ExceptionTypePrepared => b'9',
            Self::TrampolineVmReady => b'Q',
            Self::RawDtbPrepared => b'Y',
            Self::RawDtbReady => b'W',
            Self::FixMapReady => b'M',
            Self::EarlyVmPrepared => b'N',
            Self::EarlyVmReady => b'J',
            Self::VmPrepared => b'U',
            _ => b'?',
        }
    }

    #[allow(dead_code)]
    pub const fn name(self) -> &'static str {
        match self {
            Self::KernelStarted => "Kernel.Started",
            Self::BootTaskOnCpu => "BootTask.OnCpu",
            Self::BootInitFlowStarted => "BootInitFlow.Started",
            Self::KernelOnline => "Kernel.Online",
            Self::PreparePhaseReady => "PreparePhase.Ready",
            Self::PreparePhaseOnline => "PreparePhase.Online",
            Self::EntrySuccessorPhaseStarted => "EntrySuccessorPhase.Started",
            Self::EntrySuccessorPhaseReady => "EntrySuccessorPhase.Ready",
            Self::EntrySuccessorPhaseOnline => "EntrySuccessorPhase.Online",
            Self::InterruptTypePrepared => "InterruptType.Prepared",
            Self::InterruptTypeReady => "InterruptType.Ready",
            Self::KernelImagePrepared => "KernelImage.Prepared",
            Self::KernelImageReady => "KernelImage.Ready",
            Self::BootCpuPrepared => "BootCPU.Prepared",
            Self::BootCpuReady => "BootCPU.Ready",
            Self::BootCpuOnline => "BootCPU.Online",
            Self::BootCpuLocalInterruptReady => "BootCpuLocalInterrupt.Ready",
            Self::CpuGroupPrepared => "CpuGroup.Prepared",
            Self::InitStackPrepared => "InitStack.Prepared",
            Self::TrapTypePrepared => "TrapType.Prepared",
            Self::ExceptionTypePrepared => "ExceptionType.Prepared",
            Self::TrampolineVmReady => "TrampolineVm.Ready",
            Self::TrampolineVmOnline => "TrampolineVm.Online",
            Self::TrampolineVmDestroyed => "TrampolineVm.Destroyed",
            Self::RawDtbPrepared => "RawDtb.Prepared",
            Self::RawDtbReady => "RawDtb.Ready",
            Self::FixMapReady => "FixMap.Ready",
            Self::EarlyVmPrepared => "EarlyVm.Prepared",
            Self::EarlyVmReady => "EarlyVm.Ready",
            Self::EarlyVmOnline => "EarlyVm.Online",
            Self::VmPrepared => "Vm.Prepared",
            Self::VmReady => "Vm.Ready",
            Self::VmOnline => "Vm.Online",
            Self::KernelImageOnline => "KernelImage.Online",
            Self::TrapTypeReady => "TrapType.Ready",
            Self::InitStackReady => "InitStack.Ready",
            Self::InitStackOnline => "InitStack.Online",
            Self::SocPrepared => "Soc.Prepared",
            Self::EarlyDtbPrepared => "EarlyDtb.Prepared",
            Self::EarlyDtbReady => "EarlyDtb.Ready",
            Self::EarlyDtbDestroyed => "EarlyDtb.Destroyed",
            Self::PlatformCpuInfoReady => "PlatformCpuInfo.Ready",
            Self::PlatformCpuInfoOnline => "PlatformCpuInfo.Online",
            Self::PhysicalMemoryReady => "PhysicalMemory.Ready",
            Self::PhysicalMemoryOnline => "PhysicalMemory.Online",
            Self::CommandLinePrepared => "CommandLine.Prepared",
            Self::KernelCmdlineReady => "KernelCmdline.Ready",
            Self::InitMmReady => "InitMM.Ready",
            Self::EarlyIoremapReady => "EarlyIoremap.Ready",
            Self::SbiReady => "SBI.Ready",
            Self::EarlyParamReady => "EarlyParam.Ready",
            Self::MemBlockPrepared => "MemBlock.Prepared",
            Self::MemBlockReady => "MemBlock.Ready",
            Self::MemBlockOnline => "MemBlock.Online",
            Self::MemBlockOffline => "MemBlock.Offline",
            Self::SwapperVmReady => "SwapperVm.Ready",
            Self::SwapperVmOnline => "SwapperVm.Online",
            Self::EarlyVmDestroyed => "EarlyVm.Destroyed",
            Self::PrintkBufferPrepared => "PrintkBuffer.Prepared",
            Self::EarlyConPrepared => "EarlyCon.Prepared",
            Self::EarlyConReady => "EarlyCon.Ready",
            Self::EarlyConOnline => "EarlyCon.Online",
            Self::EarlyConOffline => "EarlyCon.Offline",
            Self::Serial8250ConsoleOnline => "Serial8250Console.Online",
            Self::Serial8250ConsoleIrqDrivenReady => "Serial8250Console.IrqDrivenReady",
            Self::Serial8250RxLoopbackReady => "Serial8250RxLoopback.Ready",
            Self::Serial8250RxBatchLoopbackReady => "Serial8250RxBatchLoopback.Ready",
            Self::BootConsoleOffline => "BootConsole.Offline",
            Self::CorePreparePhaseStarted => "CorePreparePhase.Started",
            Self::CorePreparePhaseReady => "CorePreparePhase.Ready",
            Self::CorePreparePhaseOnline => "CorePreparePhase.Online",
            Self::DeviceTreeReady => "DeviceTree.Ready",
            Self::ZonesReady => "Zones.Ready",
            Self::ResourceTreeReady => "ResourceTree.Ready",
            Self::CpuGroupReady => "CpuGroup.Ready",
            Self::CacheBlockInfoReady => "CacheBlockInfo.Ready",
            Self::CpuCapabilitiesReady => "CpuCapabilities.Ready",
            Self::DmaCachePolicyReady => "DmaCachePolicy.Ready",
            Self::StaticBranchReady => "StaticBranch.Ready",
            Self::CommandLineReady => "CommandLine.Ready",
            Self::SavedCommandLineReady => "SavedCommandLine.Ready",
            Self::StaticCommandLineReady => "StaticCommandLine.Ready",
            Self::SetupNrCpuIdsCheckpoint => "SetupNrCpuIds.Checkpoint",
            Self::PerCpuStaticImageReady => "PerCpuStaticImage.Ready",
            Self::PerCpuFirstChunkReady => "PerCpuFirstChunk.Ready",
            Self::PerCpuOffsetTableReady => "PerCpuOffsetTable.Ready",
            Self::PerCpuStorageReady => "PerCpuStorage.Ready",
            Self::CpuHotplugStateReady => "CpuHotplugState.Ready",
            Self::SecondParseEarlyParamCheckpoint => "SecondParseEarlyParam.Checkpoint",
            Self::BootParamReady => "BootParam.Ready",
            Self::PrintUnknownBootoptionsCheckpoint => "PrintUnknownBootoptions.Checkpoint",
            Self::PayloadParamReady => "PayloadParam.Ready",
            Self::RandomnessPrepared => "Randomness.Prepared",
            Self::PrintkBufferReady => "PrintkBuffer.Ready",
            Self::ExceptionTableReady => "ExceptionTable.Ready",
            Self::ExceptionTypeReady => "ExceptionType.Ready",
            Self::MmCoreInitPhaseStarted => "MmCoreInitPhase.Started",
            Self::MmCoreInitPhaseReady => "MmCoreInitPhase.Ready",
            Self::MmCoreInitPhaseOnline => "MmCoreInitPhase.Online",
            Self::MemoryTopologyReady => "MemoryTopology.Ready",
            Self::MemoryNodeReady => "MemoryNode.Ready",
            Self::ZoneSetReady => "ZoneSet.Ready",
            Self::PageMetadataMapReady => "PageMetadataMap.Ready",
            Self::ZonelistSetReady => "ZonelistSet.Ready",
            Self::PageAllocatorPrepared => "PageAllocator.Prepared",
            Self::MemoryDebugHardeningReady => "MemoryDebugHardening.Ready",
            Self::StackDepotReady => "StackDepot.Ready",
            Self::SwiotlbReady => "Swiotlb.Ready",
            Self::PageAllocatorReady => "PageAllocator.Ready",
            Self::PageAllocatorMemBlockHandoffReady => "PageAllocator.MemBlockHandoffReady",
            Self::SlubSubsystemPrepared => "SlubSubsystem.Prepared",
            Self::SlubCacheRegistryReady => "SlubCacheRegistry.Ready",
            Self::KmallocCachesReady => "KmallocCaches.Ready",
            Self::SlubSubsystemReady => "SlubSubsystem.Ready",
            Self::KernelGlobalAllocatorReady => "KernelGlobalAllocator.Ready",
            Self::DynamicContainerRuntimeReady => "DynamicContainerRuntime.Ready",
            Self::PageTableLockCacheReady => "PageTableLockCache.Ready",
            Self::PageTableCachesReady => "PageTableCaches.Ready",
            Self::VmapAreaCacheReady => "VmapAreaCache.Ready",
            Self::VmapAddressSpaceReady => "VmapAddressSpace.Ready",
            Self::VmapNodeSetReady => "VmapNodeSet.Ready",
            Self::VmapBlockQueuesReady => "VmapBlockQueues.Ready",
            Self::VfreeDeferredSetReady => "VfreeDeferredSet.Ready",
            Self::VmallocAllocatorReady => "VmallocAllocator.Ready",
            Self::IoremapReady => "Ioremap.Ready",
            Self::MmStructCacheReady => "MmStructCache.Ready",
            Self::MmCoreTrimmedPathsReady => "MmCoreTrimmedPaths.Ready",
            Self::SchedInitPhaseStarted => "SchedInitPhase.Started",
            Self::SchedInitPhaseReady => "SchedInitPhase.Ready",
            Self::SchedInitPhaseOnline => "SchedInitPhase.Online",
            Self::PokingInitNoop => "PokingInit.Noop",
            Self::FtraceInitTrimmedNoop => "FtraceInit.TrimmedNoop",
            Self::EarlyTraceInitDeferred => "EarlyTraceInit.Deferred",
            Self::SchedInitPreludeTrimmedPathsReady => "SchedInitPreludeTrimmedPaths.Ready",
            Self::DefaultSchedRootDomainReady => "DefaultSchedRootDomain.Ready",
            Self::BitWaitQueueTablePrepared => "BitWaitQueueTable.Prepared",
            Self::BootIdleRcuReadSidePrepared => "BootIdleRcuReadSide.Prepared",
            Self::SchedulerPrepared => "Scheduler.Prepared",
            Self::BootRunQueueReady => "BootRunQueue.Ready",
            Self::BootRunQueueLockReady => "BootRunQueueLock.Ready",
            Self::BootInitPreemptionReady => "BootInitPreemption.Ready",
            Self::BootIdleSetupReady => "BootIdleSetup.Ready",
            Self::BootIdlePiLockReady => "BootIdlePiLock.Ready",
            Self::BootIdlePreemptionReady => "BootIdlePreemption.Ready",
            Self::SchedulerReady => "Scheduler.Ready",
            Self::SchedulerOnline => "Scheduler.Online",
            Self::SchedInitIrqsDisabledCheckpoint => "SchedInitIrqsDisabled.Checkpoint",
            Self::RadixTreeReady => "RadixTree.Ready",
            Self::MapleTreeReady => "MapleTree.Ready",
            Self::WorkqueuePrepared => "Workqueue.Prepared",
            Self::SoftirqPrepared => "Softirq.Prepared",
            Self::TasksRcuPrepared => "TasksRcu.Prepared",
            Self::RcuCoreReady => "RcuCore.Ready",
            Self::TraceInitDeferred => "TraceInit.Deferred",
            Self::ContextTrackingInitTrimmedNoop => "ContextTrackingInit.TrimmedNoop",
            Self::SchedInitTraceContextBoundariesReady => "SchedInitTraceContextBoundaries.Ready",
            Self::SchedulerPickNextTaskExit => "Scheduler.PickNextTask.Exit",
            Self::SchedulerSwitchToEntry => "Scheduler.SwitchTo.Entry",
            Self::SchedulerSwitchToExit => "Scheduler.SwitchTo.Exit",
            Self::SchedulerSchedule => "Scheduler.Schedule",
            Self::SchedulerScheduleExit => "Scheduler.Schedule.Exit",
            Self::IrqTimeInitPhaseStarted => "IrqTimeInitPhase.Started",
            Self::IrqTimeInitPhaseReady => "IrqTimeInitPhase.Ready",
            Self::IrqTimeInitPhaseOnline => "IrqTimeInitPhase.Online",
            Self::IrqControllerReady => "IrqController.Ready",
            Self::RiscvIntcReady => "RiscvIntc.Ready",
            Self::RiscvIrqStackSetReady => "RiscvIrqStackSet.Ready",
            Self::IrqChipInitTablePrepared => "IrqChipInitTable.Prepared",
            Self::PlicDriverPrepared => "PlicDriver.Prepared",
            Self::IrqChipInitTableReady => "IrqChipInitTable.Ready",
            Self::IrqDispatchTreeReady => "IrqDispatchTree.Ready",
            Self::PlicReady => "Plic.Ready",
            Self::PlicIrqDomainPrepared => "PlicIrqDomain.Prepared",
            Self::PlicIrqDomainReady => "PlicIrqDomain.Ready",
            Self::IrqHandlerRegistryReady => "IrqHandlerRegistry.Ready",
            Self::TickBroadcastPrepared => "TickBroadcast.Prepared",
            Self::TickPrepared => "Tick.Prepared",
            Self::RcuInitNohzTrimmedNoop => "RcuInitNohz.TrimmedNoop",
            Self::IrqTimeTrimmedPathsPrepared => "IrqTimeTrimmedPaths.Prepared",
            Self::TimerWheelReady => "TimerWheel.Ready",
            Self::SrcuCoreReady => "SrcuCore.Ready",
            Self::HrtimerCoreReady => "HrtimerCore.Ready",
            Self::ClocksourceCorePrepared => "ClocksourceCore.Prepared",
            Self::JiffiesClocksourcePrepared => "JiffiesClocksource.Prepared",
            Self::TimekeeperReady => "Timekeeper.Ready",
            Self::RiscvTimerProviderReady => "RiscvTimerProvider.Ready",
            Self::TickBroadcastReady => "TickBroadcast.Ready",
            Self::TickReady => "Tick.Ready",
            Self::SoftirqReady => "Softirq.Ready",
            Self::RandomnessReady => "Randomness.Ready",
            Self::KfenceInitTrimmedNoop => "KfenceInit.TrimmedNoop",
            Self::IrqTimeTrimmedPathsReady => "IrqTimeTrimmedPaths.Ready",
            Self::BootStackCanaryReady => "BootStackCanary.Ready",
            Self::PerfEventCoreReady => "PerfEventCore.Ready",
            Self::ProfileCoreReady => "ProfileCore.Ready",
            Self::IpiMuxReady => "IpiMux.Ready",
            Self::SbiIpiReady => "SbiIpi.Ready",
            Self::SmpCallFunctionReady => "SmpCallFunction.Ready",
            Self::LocalIrqEnablePhaseStarted => "LocalIrqEnablePhase.Started",
            Self::LocalIrqEnablePhaseReady => "LocalIrqEnablePhase.Ready",
            Self::InterruptTypeOnline => "InterruptType.Online",
            Self::IrqOpenPreparePhaseStarted => "IrqOpenPreparePhase.Started",
            Self::IrqOpenPreparePhaseReady => "IrqOpenPreparePhase.Ready",
            Self::SlubFlushWorkqueueReady => "SlubSubsystem.FlushWorkqueueReady",
            Self::TtyLineDisciplineRegistryPrepared => "TtyLineDisciplineRegistry.Prepared",
            Self::ConsoleDriverSetPrepared => "ConsoleDriverSet.Prepared",
            Self::ConsolePrepared => "Console.Prepared",
            Self::IrqOpenPrepareTrimmedPathsPrepared => "IrqOpenPrepareTrimmedPaths.Prepared",
            Self::IrqOpenPrepareTrimmedPathsReady => "IrqOpenPrepareTrimmedPaths.Ready",
            Self::PanicLaterClearCheckpoint => "PanicLater.Clear",
            Self::LockdepInitNoop => "LockdepInit.Noop",
            Self::LockingSelftestNoop => "LockingSelftest.Noop",
            Self::InitrdBoundsTrimmed => "InitrdBounds.Trimmed",
            Self::PageAllocatorPerCpuPagesetsDeferred => "PageAllocator.PerCpuPagesetsDeferred",
            Self::NumaPolicyNoop => "NumaPolicy.Noop",
            Self::AcpiEarlyNoop => "AcpiEarly.Noop",
            Self::LateTimeInitNoop => "LateTimeInit.Noop",
            Self::SchedClockReady => "SchedClock.Ready",
            Self::DelayLoopReady => "DelayLoop.Ready",
            Self::ArchCpuFinalizeNoop => "ArchCpuFinalize.Noop",
            Self::ProcessPreparePhaseStarted => "ProcessPreparePhase.Started",
            Self::ProcessPreparePhaseReady => "ProcessPreparePhase.Ready",
            Self::RootPidNamespaceReady => "RootPidNamespace.Ready",
            Self::AnonVmaCoreReady => "AnonVmaCore.Ready",
            Self::X86EfiRuntimeSwitchTrimmed => "X86EfiRuntimeSwitch.Trimmed",
            Self::TaskCreationCorePrepared => "TaskCreationCore.Prepared",
            Self::CredentialCorePrepared => "CredentialCore.Prepared",
            Self::VectorContextPrepared => "VectorContext.Prepared",
            Self::UprobeCoreReady => "UprobeCore.Ready",
            Self::TaskCreationCoreReady => "TaskCreationCore.Ready",
            Self::ShadowCallStackInitNoop => "ShadowCallStackInit.Noop",
            Self::LockdepInitTaskNoop => "LockdepInitTask.Noop",
            Self::SignalCorePrepared => "SignalCore.Prepared",
            Self::TaskFileContextPrepared => "TaskFileContext.Prepared",
            Self::VmaCorePrepared => "VmaCore.Prepared",
            Self::NsProxyPrepared => "NsProxy.Prepared",
            Self::UtsNamespacePrepared => "UtsNamespace.Prepared",
            Self::KeyringCoreReady => "KeyringCore.Ready",
            Self::SecurityCoreReady => "SecurityCore.Ready",
            Self::ProcessPrepareTrimmedPathsPrepared => "ProcessPrepareTrimmedPaths.Prepared",
            Self::DbgLateInitNoop => "DbgLateInit.Noop",
            Self::NetNamespaceDeferred => "NetNamespace.Deferred",
            Self::PageCacheDeferred => "PageCache.Deferred",
            Self::SignalCoreSetupDeferred => "SignalCore.SetupDeferred",
            Self::SeqFileCoreDeferred => "SeqFileCore.Deferred",
            Self::ProcfsDeferred => "Procfs.Deferred",
            Self::NsfsDeferred => "Nsfs.Deferred",
            Self::PidfsDeferred => "Pidfs.Deferred",
            Self::CpusetNoop => "Cpuset.Noop",
            Self::CgroupNoop => "Cgroup.Noop",
            Self::TaskstatsNoop => "Taskstats.Noop",
            Self::DelayAccountingNoop => "DelayAccounting.Noop",
            Self::AcpiSubsystemNoop => "AcpiSubsystem.Noop",
            Self::ArchPostAcpiNoop => "ArchPostAcpi.Noop",
            Self::KcsanNoop => "Kcsan.Noop",
            Self::BootInitFlowPrepared => "BootInitFlow.Prepared",
            Self::BootInitFlowReady => "BootInitFlow.Ready",
            Self::BootInitRestInitPhaseReady => "BootInitRestInitPhase.Ready",
            Self::BootInitScheduleHandoffPhaseReady => "BootInitScheduleHandoffPhase.Ready",
            Self::BootIdleEntryPhaseReady => "BootIdleEntryPhase.Ready",
            Self::RcuSchedulerStartingReady => "RcuCore.SchedulerStartingReady",
            Self::KernelInitTaskPiLockReady => "KernelInitTaskPiLock.Ready",
            Self::KthreaddTaskPiLockReady => "KthreaddTaskPiLock.Ready",
            Self::KthreaddReadyGateWaitLockReady => "KthreaddReadyGateWaitLock.Ready",
            Self::KernelInitTaskPrepared => "KernelInitTask.Prepared",
            Self::KernelInitTaskReady => "KernelInitTask.Ready",
            Self::KernelInitTaskOnline => "KernelInitTask.Online",
            Self::KernelInitFlowOffline => "KernelInitFlow.Offline",
            Self::KernelInitFlowDestroyed => "KernelInitFlow.Destroyed",
            Self::NumaDefaultPolicyNoop => "NumaDefaultPolicy.Noop",
            Self::KthreaddTaskPrepared => "KthreaddTask.Prepared",
            Self::KthreaddTaskReady => "KthreaddTask.Ready",
            Self::KthreaddTaskOnline => "KthreaddTask.Online",
            Self::KthreaddTaskGlobalRefBound => "KthreaddTask.GlobalRefBound",
            Self::SimpleWaitQueueReady => "SimpleWaitQueue.Ready",
            Self::CompletionPrepared => "Completion.Prepared",
            Self::CompletionReady => "Completion.Ready",
            Self::CompletionOnline => "Completion.Online",
            Self::SystemStatePrepared => "SystemState.Prepared",
            Self::SystemStateReady => "SystemState.Ready",
            Self::KthreaddReadyGateReady => "KthreaddReadyGate.Ready",
            Self::KthreaddReadyGateOnline => "KthreaddReadyGate.Online",
            Self::BootIdleFlowReady => "BootIdleFlow.Ready",
            Self::PreSmpInitPhaseStarted => "PreSmpInitPhase.Started",
            Self::PreSmpInitPhaseReady => "PreSmpInitPhase.Ready",
            Self::PageAllocatorFullGfpMaskOpen => "PageAllocator.FullGfpMaskOpen",
            Self::CpuGroupPreSmpReady => "CpuGroup.PreSmpReady",
            Self::WorkqueueReady => "Workqueue.Ready",
            Self::VmstatCorePrepared => "VmstatCore.Prepared",
            Self::TasksRcuReady => "TasksRcu.Ready",
            Self::PreSmpInitcallsReady => "PreSmpInitcalls.Ready",
            Self::PreSmpBoundaryReady => "PreSmpBoundary.Ready",
            Self::SmpBringupPhaseStarted => "SmpBringupPhase.Started",
            Self::SmpBringupPhaseReady => "SmpBringupPhase.Ready",
            Self::SecondaryIdleTasksPrepared => "SecondaryIdleTasks.Prepared",
            Self::SmpbootThreadsLockReady => "SmpbootThreadsLock.Ready",
            Self::CpuHotplugSyncPrepared => "CpuHotplugSync.Prepared",
            Self::CpuHotplugReadGuardUsed => "CpuHotplugSync.CpuHotplugReadGuardUsed",
            Self::SmpbootThreadsMutexGuardUsed => "CpuHotplugSync.SmpbootThreadsMutexGuardUsed",
            Self::CpuAddRemoveLockReady => "CpuAddRemoveLock.Ready",
            Self::CpuHotplugWriteGuardUsed => "CpuStartProvider.CpuHotplugWriteGuardUsed",
            Self::CpuRunningWaitLockReady => "CpuRunningWaitLock.Ready",
            Self::CpuDoneUpWaitLockReady => "CpuDoneUpWaitLock.Ready",
            Self::CpuStartProviderReady => "CpuStartProvider.Ready",
            Self::CpuStartProviderBootDataSelected => "CpuStartProvider.BootDataSelected",
            Self::CpuStartProviderBootDataPublished => "CpuStartProvider.BootDataPublished",
            Self::CpuStartProviderHsmStartIssued => "CpuStartProvider.HsmStartIssued",
            Self::CpuStartProviderHsmStartReturned => "CpuStartProvider.HsmStartReturned",
            Self::ApEntryPreludePhaseStarted => "ApEntryPreludePhase.Started",
            Self::ApEntryPreludeBootDataConsumed => "ApEntryPreludePhase.BootDataConsumed",
            Self::ApEntryPreludeCurrentStackEstablished => {
                "ApEntryPreludePhase.CurrentStackEstablished"
            }
            Self::ApEntryPreludePhaseReady => "ApEntryPreludePhase.Ready",
            Self::ApSmpCallinPhaseStarted => "ApSmpCallinPhase.Started",
            Self::ApSmpCallinCpuRunningProduced => "ApSmpCallinPhase.CpuRunningProduced",
            Self::ApSmpCallinPhaseReady => "ApSmpCallinPhase.Ready",
            Self::ApOnlineIdlePhaseStarted => "ApOnlineIdlePhase.Started",
            Self::ApOnlineIdleDoneUpProduced => "ApOnlineIdlePhase.DoneUpProduced",
            Self::ApOnlineIdlePhaseReady => "ApOnlineIdlePhase.Ready",
            Self::CpuRunningObserved => "CpuHotplugSync.CpuRunningObserved",
            Self::CpuRunningWaitLockGuardUsed => "CpuHotplugSync.CpuRunningWaitLockGuardUsed",
            Self::SecondaryCpuStartupAckReady => "SecondaryCpuStartupAck.Ready",
            Self::CpuDoneUpObserved => "CpuHotplugSync.DoneUpObserved",
            Self::CpuDoneUpWaitLockGuardUsed => "CpuHotplugSync.DoneUpWaitLockGuardUsed",
            Self::SecondaryCpusOnline => "CpuGroup.SecondaryCpusOnline",
            Self::SecondaryCpuApLocalSyncSummary => "SecondaryCpuOnlineAck.ApLocalSyncSummary",
            Self::SecondaryCpuOnlineAckReady => "SecondaryCpuOnlineAck.Ready",
            Self::SmpBringupBoundaryReady => "SmpBringupBoundary.Ready",
            Self::RuntimeCorePhaseStarted => "RuntimeCorePhase.Started",
            Self::RuntimeCorePhaseReady => "RuntimeCorePhase.Ready",
            Self::SchedulerSmpReady => "Scheduler.SmpReady",
            Self::WorkqueueTopologyReady => "Workqueue.TopologyReady",
            Self::AsyncCoreDeferredReady => "AsyncCore.DeferredReady",
            Self::PadataCoreDeferredReady => "PadataCore.DeferredReady",
            Self::PageAllocatorLateReady => "PageAllocator.LateReady",
            Self::RuntimeCoreBoundaryReady => "RuntimeCoreBoundary.Ready",
            Self::InitcallPhaseStarted => "InitcallPhase.Started",
            Self::InitcallPhaseReady => "InitcallPhase.Ready",
            Self::CpusetSmpTrimmedReady => "CpusetSmp.TrimmedReady",
            Self::DriverCoreDeferredReady => "DriverCore.DeferredReady",
            Self::IrqProcViewDeferredReady => "IrqProcView.DeferredReady",
            Self::CtorTableReady => "CtorTable.Ready",
            Self::OfPlatformDefaultPopulateScanComplete => "OfPlatformDefaultPopulate.ScanComplete",
            Self::VirtioBusReady => "VirtioBus.Ready",
            Self::VirtioBusDeviceAdded => "VirtioBus.DeviceAdded",
            Self::VirtioBlkReady => "VirtioBlk.Ready",
            Self::VirtioBlkReadReady => "VirtioBlk.ReadReady",
            Self::VirtioBlkLiveReadSubmitted => "VirtioBlk.LiveReadSubmitted",
            Self::VirtioBlkLiveReadCompleted => "VirtioBlk.LiveReadCompleted",
            Self::VirtioRngEntropyReady => "VirtioRng.EntropyReady",
            Self::InitcallTableReady => "InitcallTable.Ready",
            Self::Serial8250ConsoleBurstIrqTxReady => "Serial8250ConsoleBurstIrqTx.Ready",
            Self::Serial8250ConsoleLongIrqTxReady => "Serial8250ConsoleLongIrqTx.Ready",
            Self::Serial8250ConsoleLongBurstIrqTxReady => "Serial8250ConsoleLongBurstIrqTx.Ready",
            Self::Serial8250ConsoleTxQuiesceReady => "Serial8250ConsoleTxQuiesce.Ready",
            Self::TtyXmitFifoProbeReady => "TtyXmitFifoProbe.Ready",
            Self::TtyWriteRuntimeTxReady => "TtyWriteRuntimeTx.Ready",
            Self::TtyWriteBatchRuntimeTxReady => "TtyWriteBatchRuntimeTx.Ready",
            Self::InitcallBoundaryReady => "InitcallBoundary.Ready",
            Self::RootfsPhaseStarted => "RootfsPhase.Started",
            Self::RootfsPhaseReady => "RootfsPhase.Ready",
            Self::KUnitRuntimeTrimmedReady => "KUnitRuntime.TrimmedReady",
            Self::InitramfsSyncDeferredReady => "InitramfsSync.DeferredReady",
            Self::RootfsConsoleDeferredReady => "RootfsConsole.DeferredReady",
            Self::RootfsPrepareNamespacePathsReady => "RootfsPrepareNamespacePaths.Ready",
            Self::RamdiskExecuteCommandEaccessCheckpoint => {
                "RamdiskExecuteCommand.EaccessCheckpoint"
            }
            Self::RootFSOnline => "RootFS.Online",
            Self::IntegrityKeysDeferredReady => "IntegrityKeys.DeferredReady",
            Self::RootfsBoundaryReady => "RootfsBoundary.Ready",
            Self::FinalizePhaseStarted => "FinalizePhase.Started",
            Self::FinalizePhaseReady => "FinalizePhase.Ready",
            Self::AsyncFullSyncDeferredReady => "AsyncFullSync.DeferredReady",
            Self::SystemStateFreeingInitmemCheckpoint => "SystemState.FreeingInitmemCheckpoint",
            Self::InitMemoryCleanupDeferredReady => "InitMemoryCleanup.DeferredReady",
            Self::KernelMappingProtectionDeferredReady => "KernelMappingProtection.DeferredReady",
            Self::PtiFinalizeTrimmedReady => "PtiFinalize.TrimmedReady",
            Self::SystemStateOnline => "SystemState.Online",
            Self::RcuInkernelBootEnded => "RcuCore.InkernelBootEnded",
            Self::RcuBootEndReady => "RcuBootEnd.Ready",
            Self::SysctlArgsDeferredReady => "SysctlArgs.DeferredReady",
            Self::FinalizeBoundaryReady => "FinalizeBoundary.Ready",
            Self::BreakpointExceptionHandled => "BreakpointException.Handled",
            Self::UserBootMainElfReady => "UserBoot.MainElfReady",
            Self::UserBootInterpreterReady => "UserBoot.InterpreterReady",
            Self::UserBootInitAttemptFailed => "UserBoot.InitAttemptFailed",
            Self::UserBootAddressSpaceSetupStart => "UserBoot.AddressSpaceSetupStart",
            Self::UserAppFlowPrepared => "UserAppFlow.Prepared",
            Self::UserAppFlowReady => "UserAppFlow.Ready",
            Self::UserAppFlowOnline => "UserAppFlow.Online",
            Self::UserAppFlowEnterUserMode => "UserAppFlow.EnterUserMode",
            Self::UserAddressSpaceReady => "UserAddressSpace.Ready",
            Self::SyscallTableExecveArgsReady => "SyscallTable.ExecveArgsReady",
            Self::UserExecMainElfReady => "UserExec.MainElfReady",
            Self::UserExecInterpreterReady => "UserExec.InterpreterReady",
            Self::UserExecAddressSpaceReady => "UserExec.AddressSpaceReady",
            Self::UserExecTrapFrameReady => "UserExec.TrapFrameReady",
            Self::UserExecSatpReady => "UserExec.SatpReady",
            Self::UserExecContextReplaced => "UserExec.ContextReplaced",
            Self::UserExecSatpSwitched => "UserExec.SatpSwitched",
            Self::UserExecReturnFrameReady => "UserExec.ReturnFrameReady",
            Self::SyscallTableOpenAt => "SyscallTable.OpenAt",
            Self::SyscallTableRead => "SyscallTable.Read",
            Self::SyscallTableWrite => "SyscallTable.Write",
            Self::SyscallTableWritev => "SyscallTable.Writev",
            Self::SyscallTableClose => "SyscallTable.Close",
            Self::SyscallTableNewFstatAt => "SyscallTable.NewFstatAt",
            Self::SyscallTableSetTidAddress => "SyscallTable.SetTidAddress",
            Self::SyscallTableClone => "SyscallTable.Clone",
            Self::SyscallTableCloneVforkVm => "SyscallTable.CloneVforkVm",
            Self::SyscallTableCloneVforkPidfd => "SyscallTable.CloneVforkPidfd",
            Self::FilesStructPidfdInstall => "FilesStruct.PidfdInstall",
            Self::UserCloneVforkChildHandoff => "UserClone.VforkChildHandoff",
            Self::UserCloneVforkNextChildAccepted => "UserClone.VforkNextChildAccepted",
            Self::SyscallTableRtSigtimedwait => "SyscallTable.RtSigtimedwait",
            Self::UserSignalWaitSleep => "UserSignalWait.Sleep",
            Self::UserSignalWaitWakeSigchld => "UserSignalWait.WakeSigchld",
            Self::UserPidfdReady => "UserPidfd.Ready",
            Self::SyscallTableRtSigtimedwaitReturnSignal => {
                "SyscallTable.RtSigtimedwaitReturnSignal"
            }
            Self::SyscallTableWait4 => "SyscallTable.Wait4",
            Self::UserChildParentWaitResumed => "UserChild.ParentWaitResumed",
            Self::UserCloneVforkParentResumed => "UserClone.VforkParentResumed",
            Self::UserChildRecordArchived => "UserChildRecord.Archived",
            Self::UserTaskRecordReleased => "UserTaskRecord.Released",
            Self::UserChildRecordReaped => "UserChildRecord.Reaped",
            Self::SyscallTableExit => "SyscallTable.Exit",
            Self::EntrySuccessorPhasePrepared => "EntrySuccessorPhase.Prepared",
            Self::CorePreparePhasePrepared => "CorePreparePhase.Prepared",
            Self::MmCoreInitPhasePrepared => "MmCoreInitPhase.Prepared",
            Self::SchedInitPhasePrepared => "SchedInitPhase.Prepared",
            Self::IrqTimeInitPhasePrepared => "IrqTimeInitPhase.Prepared",
            Self::LocalIrqEnablePhasePrepared => "LocalIrqEnablePhase.Prepared",
            Self::LocalIrqEnablePhaseOnline => "LocalIrqEnablePhase.Online",
            Self::IrqOpenPreparePhasePrepared => "IrqOpenPreparePhase.Prepared",
            Self::IrqOpenPreparePhaseOnline => "IrqOpenPreparePhase.Online",
            Self::ProcessPreparePhasePrepared => "ProcessPreparePhase.Prepared",
            Self::ProcessPreparePhaseOnline => "ProcessPreparePhase.Online",
            Self::BootInitFlowOnline => "BootInitFlow.Online",
            Self::BootInitRestInitPhaseStarted => "BootInitRestInitPhase.Started",
            Self::BootInitRestInitPhasePrepared => "BootInitRestInitPhase.Prepared",
            Self::BootInitRestInitPhaseOnline => "BootInitRestInitPhase.Online",
            Self::BootInitScheduleHandoffPhaseStarted => "BootInitScheduleHandoffPhase.Started",
            Self::BootInitScheduleHandoffPhasePrepared => "BootInitScheduleHandoffPhase.Prepared",
            Self::BootInitScheduleHandoffPhaseOnline => "BootInitScheduleHandoffPhase.Online",
            Self::BootIdleEntryPhaseStarted => "BootIdleEntryPhase.Started",
            Self::BootIdleEntryPhasePrepared => "BootIdleEntryPhase.Prepared",
            Self::BootIdleEntryPhaseOnline => "BootIdleEntryPhase.Online",
            Self::PreSmpInitPhasePrepared => "PreSmpInitPhase.Prepared",
            Self::PreSmpInitPhaseOnline => "PreSmpInitPhase.Online",
            Self::SmpBringupPhasePrepared => "SmpBringupPhase.Prepared",
            Self::SmpBringupPhaseOnline => "SmpBringupPhase.Online",
            Self::RuntimeCorePhasePrepared => "RuntimeCorePhase.Prepared",
            Self::RuntimeCorePhaseOnline => "RuntimeCorePhase.Online",
            Self::InitcallPhasePrepared => "InitcallPhase.Prepared",
            Self::InitcallPhaseOnline => "InitcallPhase.Online",
            Self::RootfsPhasePrepared => "RootfsPhase.Prepared",
            Self::RootfsPhaseOnline => "RootfsPhase.Online",
            Self::FinalizePhasePrepared => "FinalizePhase.Prepared",
            Self::FinalizePhaseOnline => "FinalizePhase.Online",
            Self::ApEntryPreludePhasePrepared => "ApEntryPreludePhase.Prepared",
            Self::ApEntryPreludePhaseOnline => "ApEntryPreludePhase.Online",
            Self::ApSmpCallinPhasePrepared => "ApSmpCallinPhase.Prepared",
            Self::ApSmpCallinPhaseOnline => "ApSmpCallinPhase.Online",
            Self::ApOnlineIdlePhasePrepared => "ApOnlineIdlePhase.Prepared",
            Self::ApOnlineIdlePhaseOnline => "ApOnlineIdlePhase.Online",
            Self::PayloadPreparePhaseStarted => "PayloadPreparePhase.Started",
            Self::PayloadPreparePhasePrepared => "PayloadPreparePhase.Prepared",
            Self::PayloadPreparePhaseReady => "PayloadPreparePhase.Ready",
            Self::PayloadPreparePhaseOnline => "PayloadPreparePhase.Online",
            Self::PayloadHandoffPreparePhaseStarted => "PayloadHandoffPreparePhase.Started",
            Self::PayloadHandoffPreparePhasePrepared => "PayloadHandoffPreparePhase.Prepared",
            Self::PayloadHandoffPreparePhaseReady => "PayloadHandoffPreparePhase.Ready",
            Self::PayloadHandoffPreparePhaseOnline => "PayloadHandoffPreparePhase.Online",
            Self::KernelInitFlowPayloadHandoffCommitted => "KernelInitFlow.PayloadHandoffCommitted",
            Self::UserStackGrowComplete => "UserStack.GrowComplete",
            Self::UserStackGrowRejected => "UserStack.GrowRejected",
        }
    }
}
