<script lang="ts">
  import type { AnimationTrace } from './types';

  let { animation }: { animation: AnimationTrace } = $props();
  const request = $derived(animation.trace.root_request);
</script>

<svelte:head>
  <meta name="color-scheme" content="light dark" />
</svelte:head>

<section class="player-shell" aria-labelledby="trace-title">
  <header>
    <p class="eyebrow">tools2 · deterministic Signal trace</p>
    <h1 id="trace-title">{request.target}.{request.signal}</h1>
    <p class="lede">The offline player bundle is ready. Deterministic frames are generated by the animate stage.</p>
  </header>
  <dl class="trace-meta">
    <div><dt>Source</dt><dd>{request.source}</dd></div>
    <div><dt>Verdict</dt><dd>{animation.trace.verdict}</dd></div>
    <div><dt>Signals</dt><dd>{animation.trace.total_steps}</dd></div>
    <div><dt>Protocol</dt><dd>{animation.schema} v{animation.version}</dd></div>
  </dl>
  <div class="stage" aria-label="Signal animation canvas">
    <p>Initial frame pending</p>
  </div>
  <footer title={animation.inputs.model_fingerprint}>{animation.source}</footer>
</section>
