use crate::objects::{
    boot_param::BootParam,
    cache_block_info::CacheBlockInfo,
    command_line::{CommandLine, SavedCommandLine, StaticCommandLine},
    config::Config,
    cpu_capabilities::CpuCapabilities,
    cpu_group::CpuGroup,
    cpu_hotplug::CpuHotplugState,
    cpu_id_map::CpuIdMap,
    device_tree::DeviceTree,
    dma_cache_policy::DmaCachePolicy,
    early_dtb::EarlyDtb,
    early_ioremap::EarlyIoremap,
    early_param::EarlyParam,
    event_stream::EventStream,
    exception_stream::ExceptionStream,
    exception_table::ExceptionTable,
    fix_map::FixMap,
    init_mm::InitMm,
    init_stack::InitStack,
    init_task::InitTask,
    interrupt_stream::InterruptStream,
    irq_time::{
        HrtimerCore, IrqController, IrqDispatchTree, RiscvTimerProvider, SbiIpi, SmpCallFunction,
        Tick, Timekeeper, TimerWheel,
    },
    kernel_cmdline::KernelCmdline,
    kernel_image::KernelImage,
    lds::Lds,
    maple_tree::MapleTree,
    memblock::MemBlock,
    mm_core::{
        MemoryDebugHardening, MemoryTopology, MmStructCache, PageAllocator, PageTableCaches,
        SlubAllocator, StackDepot, Swiotlb, VmallocAllocator,
    },
    params::Params,
    payload_param::PayloadParam,
    per_cpu_storage::PerCpuStorage,
    physical_memory::PhysicalMemory,
    platform_cpu_info::PlatformCpuInfo,
    radix_tree::RadixTree,
    randomness::Randomness,
    raw_dtb::RawDtb,
    rcu::RcuCore,
    resource_tree::ResourceTree,
    root_stream::RootStream,
    sbi::Sbi,
    scheduler::Scheduler,
    softirq::Softirq,
    static_branch::StaticBranch,
    static_objects::StaticObjects,
    vm::Vm,
    workqueue::Workqueue,
    zones::Zones,
};

pub struct Context {
    pub config: Config,
    pub static_objects: StaticObjects,
    pub lds: Lds,

    pub interrupt_stream: InterruptStream,
    pub kernel_image: KernelImage,
    pub root_stream: RootStream,
    pub cpu_group: CpuGroup,
    pub init_task: InitTask,
    pub init_stack: InitStack,
    pub event_stream: EventStream,
    pub exception_stream: ExceptionStream,
    pub vm: Vm,
    pub raw_dtb: RawDtb,
    pub fix_map: FixMap,

    pub early_dtb: EarlyDtb,
    pub platform_cpu_info: PlatformCpuInfo,
    pub physical_memory: PhysicalMemory,
    pub cpu_id_map: CpuIdMap,
    pub command_line: CommandLine,
    pub kernel_cmdline: KernelCmdline,
    pub init_mm: InitMm,
    pub early_ioremap: EarlyIoremap,
    pub sbi: Sbi,
    pub early_param: EarlyParam,
    pub params: Params,
    pub memblock: MemBlock,

    pub device_tree: DeviceTree,
    pub zones: Zones,
    pub resource_tree: ResourceTree,
    pub cache_block_info: CacheBlockInfo,
    pub cpu_capabilities: CpuCapabilities,
    pub dma_cache_policy: DmaCachePolicy,
    pub static_branch: StaticBranch,
    pub saved_command_line: SavedCommandLine,
    pub static_command_line: StaticCommandLine,
    pub per_cpu_storage: PerCpuStorage,
    pub cpu_hotplug_state: CpuHotplugState,
    pub boot_param: BootParam,
    pub payload_param: PayloadParam,
    pub randomness: Randomness,
    pub exception_table: ExceptionTable,

    pub memory_topology: MemoryTopology,
    pub page_allocator: PageAllocator,
    pub memory_debug_hardening: MemoryDebugHardening,
    pub stack_depot: StackDepot,
    pub swiotlb: Swiotlb,
    pub slub_allocator: SlubAllocator,
    pub page_table_caches: PageTableCaches,
    pub vmalloc_allocator: VmallocAllocator,
    pub mm_struct_cache: MmStructCache,

    pub scheduler: Scheduler,
    pub radix_tree: RadixTree,
    pub maple_tree: MapleTree,
    pub workqueue: Workqueue,
    pub softirq: Softirq,
    pub rcu_core: RcuCore,

    pub irq_controller: IrqController,
    pub irq_dispatch_tree: IrqDispatchTree,
    pub tick: Tick,
    pub timer_wheel: TimerWheel,
    pub hrtimer_core: HrtimerCore,
    pub timekeeper: Timekeeper,
    pub riscv_timer_provider: RiscvTimerProvider,
    pub sbi_ipi: SbiIpi,
    pub smp_call_function: SmpCallFunction,
}

impl Context {
    pub const fn new() -> Self {
        Self {
            config: Config::new(),
            static_objects: StaticObjects::new(),
            lds: Lds::new(),
            interrupt_stream: InterruptStream::new(),
            kernel_image: KernelImage::new(),
            root_stream: RootStream::new(),
            cpu_group: CpuGroup::new(),
            init_task: InitTask::new(),
            init_stack: InitStack::new(),
            event_stream: EventStream::new(),
            exception_stream: ExceptionStream::new(),
            vm: Vm::new(),
            raw_dtb: RawDtb::new(),
            fix_map: FixMap::new(),
            early_dtb: EarlyDtb::new(),
            platform_cpu_info: PlatformCpuInfo::new(),
            physical_memory: PhysicalMemory::new(),
            cpu_id_map: CpuIdMap::new(),
            command_line: CommandLine::new(),
            kernel_cmdline: KernelCmdline::new(),
            init_mm: InitMm::new(),
            early_ioremap: EarlyIoremap::new(),
            sbi: Sbi::new(),
            early_param: EarlyParam::new(),
            params: Params::new(),
            memblock: MemBlock::new(),
            device_tree: DeviceTree::new(),
            zones: Zones::new(),
            resource_tree: ResourceTree::new(),
            cache_block_info: CacheBlockInfo::new(),
            cpu_capabilities: CpuCapabilities::new(),
            dma_cache_policy: DmaCachePolicy::new(),
            static_branch: StaticBranch::new(),
            saved_command_line: SavedCommandLine::new(),
            static_command_line: StaticCommandLine::new(),
            per_cpu_storage: PerCpuStorage::new(),
            cpu_hotplug_state: CpuHotplugState::new(),
            boot_param: BootParam::new(),
            payload_param: PayloadParam::new(),
            randomness: Randomness::new(),
            exception_table: ExceptionTable::new(),
            memory_topology: MemoryTopology::new(),
            page_allocator: PageAllocator::new(),
            memory_debug_hardening: MemoryDebugHardening::new(),
            stack_depot: StackDepot::new(),
            swiotlb: Swiotlb::new(),
            slub_allocator: SlubAllocator::new(),
            page_table_caches: PageTableCaches::new(),
            vmalloc_allocator: VmallocAllocator::new(),
            mm_struct_cache: MmStructCache::new(),
            scheduler: Scheduler::new(),
            radix_tree: RadixTree::new(),
            maple_tree: MapleTree::new(),
            workqueue: Workqueue::new(),
            softirq: Softirq::new(),
            rcu_core: RcuCore::new(),
            irq_controller: IrqController::new(),
            irq_dispatch_tree: IrqDispatchTree::new(),
            tick: Tick::new(),
            timer_wheel: TimerWheel::new(),
            hrtimer_core: HrtimerCore::new(),
            timekeeper: Timekeeper::new(),
            riscv_timer_provider: RiscvTimerProvider::new(),
            sbi_ipi: SbiIpi::new(),
            smp_call_function: SmpCallFunction::new(),
        }
    }
}

static mut CONTEXT: Context = Context::new();

pub fn context() -> &'static mut Context {
    // SAFETY: the current boot path is single-hart and system-exclusive. The
    // context owns long-lived resource objects that must survive address-space
    // switches during startup.
    unsafe { &mut *core::ptr::addr_of_mut!(CONTEXT) }
}

pub fn context_ref() -> &'static Context {
    // SAFETY: read-only access is used for boundary checks before the mutable
    // phase path starts mutating the context.
    unsafe { &*core::ptr::addr_of!(CONTEXT) }
}
