use crate::objects::{
    boot_param::BootParam,
    cache_block_info::CacheBlockInfo,
    command_line::{CommandLine, SavedCommandLine, StaticCommandLine},
    config::Config,
    cpu_capabilities::CpuCapabilities,
    cpu_group::CpuGroup,
    cpu_hotplug::CpuHotplugState,
    cpu_id_map::CpuIdMap,
    device_tree::DeviceTree,
    dma_cache_policy::DmaCachePolicy,
    early_dtb::EarlyDtb,
    early_ioremap::EarlyIoremap,
    early_param::EarlyParam,
    event_stream::EventStream,
    exception_stream::ExceptionStream,
    exception_table::ExceptionTable,
    fix_map::FixMap,
    init_mm::InitMm,
    init_stack::InitStack,
    init_task::InitTask,
    interrupt_stream::InterruptStream,
    irq_open::{Console, DelayLoop, SchedClock},
    irq_time::{
        HrtimerCore, IpiMux, IrqController, IrqDispatchTree, Plic, RiscvIntc, RiscvTimerProvider,
        SbiIpi, SmpCallFunction, Tick, Timekeeper, TimerWheel,
    },
    kernel_cmdline::KernelCmdline,
    kernel_image::KernelImage,
    lds::Lds,
    maple_tree::MapleTree,
    memblock::MemBlock,
    mm_core::{
        MemoryDebugHardening, MemoryTopology, MmStructCache, PageAllocator, PageTableCaches,
        SlubAllocator, StackDepot, Swiotlb, VmallocAllocator,
    },
    params::Params,
    payload_param::PayloadParam,
    per_cpu_storage::PerCpuStorage,
    physical_memory::PhysicalMemory,
    platform_cpu_info::PlatformCpuInfo,
    pre_smp_init::{PreSmpInitBoundary, PreSmpInitcallTable, VmstatCore},
    process_prepare::{
        AnonVmaCore, CredentialCore, KeyringCore, NsProxy, RootPidNamespace, SecurityCore,
        SignalCore, TaskCreationCore, TaskFileContext, UtsNamespace, VmaCore,
    },
    radix_tree::RadixTree,
    randomness::Randomness,
    raw_dtb::RawDtb,
    rcu::RcuCore,
    resource_tree::ResourceTree,
    rest_init::{
        BootIdleRuntime, KernelInitAffinity, KernelInitDispatchGate, KernelInitTask,
        KthreaddReadyGate, KthreaddTask, RcuSchedulerStart, SystemState,
    },
    root_stream::RootStream,
    runtime_core::{AsyncCoreDeferred, PadataCoreDeferred, RuntimeCoreBoundary},
    sbi::Sbi,
    scheduler::Scheduler,
    smp_bringup::{
        CpuHotplugSyncSet, CpuStartProvider, SecondaryCpuOnlineAck, SecondaryCpuStartupAck,
        SecondaryIdleTaskSet, SmpBringupBoundary,
    },
    softirq::Softirq,
    static_branch::StaticBranch,
    static_objects::StaticObjects,
    vm::Vm,
    workqueue::Workqueue,
    zones::Zones,
};

pub struct Context {
    pub config: Config,
    pub static_objects: StaticObjects,
    pub lds: Lds,

    pub interrupt_stream: InterruptStream,
    pub kernel_image: KernelImage,
    pub root_stream: RootStream,
    pub cpu_group: CpuGroup,
    pub init_task: InitTask,
    pub init_stack: InitStack,
    pub event_stream: EventStream,
    pub exception_stream: ExceptionStream,
    pub vm: Vm,
    pub raw_dtb: RawDtb,
    pub fix_map: FixMap,

    pub early_dtb: EarlyDtb,
    pub platform_cpu_info: PlatformCpuInfo,
    pub physical_memory: PhysicalMemory,
    pub cpu_id_map: CpuIdMap,
    pub command_line: CommandLine,
    pub kernel_cmdline: KernelCmdline,
    pub init_mm: InitMm,
    pub early_ioremap: EarlyIoremap,
    pub sbi: Sbi,
    pub early_param: EarlyParam,
    pub params: Params,
    pub memblock: MemBlock,

    pub device_tree: DeviceTree,
    pub zones: Zones,
    pub resource_tree: ResourceTree,
    pub cache_block_info: CacheBlockInfo,
    pub cpu_capabilities: CpuCapabilities,
    pub dma_cache_policy: DmaCachePolicy,
    pub static_branch: StaticBranch,
    pub saved_command_line: SavedCommandLine,
    pub static_command_line: StaticCommandLine,
    pub per_cpu_storage: PerCpuStorage,
    pub cpu_hotplug_state: CpuHotplugState,
    pub boot_param: BootParam,
    pub payload_param: PayloadParam,
    pub randomness: Randomness,
    pub exception_table: ExceptionTable,

    pub memory_topology: MemoryTopology,
    pub page_allocator: PageAllocator,
    pub memory_debug_hardening: MemoryDebugHardening,
    pub stack_depot: StackDepot,
    pub swiotlb: Swiotlb,
    pub slub_allocator: SlubAllocator,
    pub page_table_caches: PageTableCaches,
    pub vmalloc_allocator: VmallocAllocator,
    pub mm_struct_cache: MmStructCache,

    pub scheduler: Scheduler,
    pub radix_tree: RadixTree,
    pub maple_tree: MapleTree,
    pub workqueue: Workqueue,
    pub softirq: Softirq,
    pub rcu_core: RcuCore,

    pub irq_controller: IrqController,
    pub riscv_intc: RiscvIntc,
    pub irq_dispatch_tree: IrqDispatchTree,
    pub plic: Plic,
    pub tick: Tick,
    pub timer_wheel: TimerWheel,
    pub hrtimer_core: HrtimerCore,
    pub timekeeper: Timekeeper,
    pub riscv_timer_provider: RiscvTimerProvider,
    pub ipi_mux: IpiMux,
    pub sbi_ipi: SbiIpi,
    pub smp_call_function: SmpCallFunction,

    pub console: Console,
    pub sched_clock: SchedClock,
    pub delay_loop: DelayLoop,

    pub root_pid_namespace: RootPidNamespace,
    pub anon_vma_core: AnonVmaCore,
    pub task_creation_core: TaskCreationCore,
    pub credential_core: CredentialCore,
    pub signal_core: SignalCore,
    pub task_file_context: TaskFileContext,
    pub vma_core: VmaCore,
    pub ns_proxy: NsProxy,
    pub uts_namespace: UtsNamespace,
    pub keyring_core: KeyringCore,
    pub security_core: SecurityCore,

    pub rcu_scheduler_start: RcuSchedulerStart,
    pub kernel_init_task: KernelInitTask,
    pub kernel_init_affinity: KernelInitAffinity,
    pub kthreadd_task: KthreaddTask,
    pub system_state: SystemState,
    pub kthreadd_ready_gate: KthreaddReadyGate,
    pub kernel_init_dispatch_gate: KernelInitDispatchGate,
    pub boot_idle_runtime: BootIdleRuntime,
    pub vmstat_core: VmstatCore,
    pub pre_smp_initcalls: PreSmpInitcallTable,
    pub pre_smp_boundary: PreSmpInitBoundary,
    pub secondary_idle_tasks: SecondaryIdleTaskSet,
    pub cpu_hotplug_sync: CpuHotplugSyncSet,
    pub cpu_start_provider: CpuStartProvider,
    pub secondary_cpu_startup_ack: SecondaryCpuStartupAck,
    pub secondary_cpu_online_ack: SecondaryCpuOnlineAck,
    pub smp_bringup_boundary: SmpBringupBoundary,
    pub async_core_deferred: AsyncCoreDeferred,
    pub padata_core_deferred: PadataCoreDeferred,
    pub runtime_core_boundary: RuntimeCoreBoundary,
}

impl Context {
    pub const fn new() -> Self {
        Self {
            config: Config::new(),
            static_objects: StaticObjects::new(),
            lds: Lds::new(),
            interrupt_stream: InterruptStream::new(),
            kernel_image: KernelImage::new(),
            root_stream: RootStream::new(),
            cpu_group: CpuGroup::new(),
            init_task: InitTask::new(),
            init_stack: InitStack::new(),
            event_stream: EventStream::new(),
            exception_stream: ExceptionStream::new(),
            vm: Vm::new(),
            raw_dtb: RawDtb::new(),
            fix_map: FixMap::new(),
            early_dtb: EarlyDtb::new(),
            platform_cpu_info: PlatformCpuInfo::new(),
            physical_memory: PhysicalMemory::new(),
            cpu_id_map: CpuIdMap::new(),
            command_line: CommandLine::new(),
            kernel_cmdline: KernelCmdline::new(),
            init_mm: InitMm::new(),
            early_ioremap: EarlyIoremap::new(),
            sbi: Sbi::new(),
            early_param: EarlyParam::new(),
            params: Params::new(),
            memblock: MemBlock::new(),
            device_tree: DeviceTree::new(),
            zones: Zones::new(),
            resource_tree: ResourceTree::new(),
            cache_block_info: CacheBlockInfo::new(),
            cpu_capabilities: CpuCapabilities::new(),
            dma_cache_policy: DmaCachePolicy::new(),
            static_branch: StaticBranch::new(),
            saved_command_line: SavedCommandLine::new(),
            static_command_line: StaticCommandLine::new(),
            per_cpu_storage: PerCpuStorage::new(),
            cpu_hotplug_state: CpuHotplugState::new(),
            boot_param: BootParam::new(),
            payload_param: PayloadParam::new(),
            randomness: Randomness::new(),
            exception_table: ExceptionTable::new(),
            memory_topology: MemoryTopology::new(),
            page_allocator: PageAllocator::new(),
            memory_debug_hardening: MemoryDebugHardening::new(),
            stack_depot: StackDepot::new(),
            swiotlb: Swiotlb::new(),
            slub_allocator: SlubAllocator::new(),
            page_table_caches: PageTableCaches::new(),
            vmalloc_allocator: VmallocAllocator::new(),
            mm_struct_cache: MmStructCache::new(),
            scheduler: Scheduler::new(),
            radix_tree: RadixTree::new(),
            maple_tree: MapleTree::new(),
            workqueue: Workqueue::new(),
            softirq: Softirq::new(),
            rcu_core: RcuCore::new(),
            irq_controller: IrqController::new(),
            riscv_intc: RiscvIntc::new(),
            irq_dispatch_tree: IrqDispatchTree::new(),
            plic: Plic::new(),
            tick: Tick::new(),
            timer_wheel: TimerWheel::new(),
            hrtimer_core: HrtimerCore::new(),
            timekeeper: Timekeeper::new(),
            riscv_timer_provider: RiscvTimerProvider::new(),
            ipi_mux: IpiMux::new(),
            sbi_ipi: SbiIpi::new(),
            smp_call_function: SmpCallFunction::new(),
            console: Console::new(),
            sched_clock: SchedClock::new(),
            delay_loop: DelayLoop::new(),
            root_pid_namespace: RootPidNamespace::new(),
            anon_vma_core: AnonVmaCore::new(),
            task_creation_core: TaskCreationCore::new(),
            credential_core: CredentialCore::new(),
            signal_core: SignalCore::new(),
            task_file_context: TaskFileContext::new(),
            vma_core: VmaCore::new(),
            ns_proxy: NsProxy::new(),
            uts_namespace: UtsNamespace::new(),
            keyring_core: KeyringCore::new(),
            security_core: SecurityCore::new(),
            rcu_scheduler_start: RcuSchedulerStart::new(),
            kernel_init_task: KernelInitTask::new(),
            kernel_init_affinity: KernelInitAffinity::new(),
            kthreadd_task: KthreaddTask::new(),
            system_state: SystemState::new(),
            kthreadd_ready_gate: KthreaddReadyGate::new(),
            kernel_init_dispatch_gate: KernelInitDispatchGate::new(),
            boot_idle_runtime: BootIdleRuntime::new(),
            vmstat_core: VmstatCore::new(),
            pre_smp_initcalls: PreSmpInitcallTable::new(),
            pre_smp_boundary: PreSmpInitBoundary::new(),
            secondary_idle_tasks: SecondaryIdleTaskSet::new(),
            cpu_hotplug_sync: CpuHotplugSyncSet::new(),
            cpu_start_provider: CpuStartProvider::new(),
            secondary_cpu_startup_ack: SecondaryCpuStartupAck::new(),
            secondary_cpu_online_ack: SecondaryCpuOnlineAck::new(),
            smp_bringup_boundary: SmpBringupBoundary::new(),
            async_core_deferred: AsyncCoreDeferred::new(),
            padata_core_deferred: PadataCoreDeferred::new(),
            runtime_core_boundary: RuntimeCoreBoundary::new(),
        }
    }
}

static mut CONTEXT: Context = Context::new();

pub fn context() -> &'static mut Context {
    // SAFETY: the current boot path is single-hart and system-exclusive. The
    // context owns long-lived resource objects that must survive address-space
    // switches during startup.
    unsafe { &mut *core::ptr::addr_of_mut!(CONTEXT) }
}

pub fn context_ref() -> &'static Context {
    // SAFETY: read-only access is used for boundary checks before the mutable
    // phase path starts mutating the context.
    unsafe { &*core::ptr::addr_of!(CONTEXT) }
}
